In [331]:
# БЕТА-ВЕРСИЯ ГОТОВОЙ ПРОГРАММЫ
from tkinter import *
from tkinter import ttk

root = Tk()
root.geometry('1000x600')
root.title('Соревнования по дартс')
#root.attributes('-fullscreen', True)

# базовые координаты и смещения
xstart = 10
xmove = 70
ystart = 40
ymove = 20
padx_value = 35
pady_value = 10

ent_xstart = 700
ent_ystart = 80
ent_ymove = 35


# -------------------------------------------------------------------------------------------------------------------------
# ЗАПУСК ПЕРВОГО ОКНА (ПОСЛЕ СТАРТОВОГО ПРИВЕТСТВИЯ)
registration_window = ttk.Frame(root, height = 600, width = 1000)

def start_registration():
    start_lbl.destroy()
    btn_start.destroy()
    registration_window.pack()
    
    heading_lbl.place(x=100, y=10) # "Список участников"
    enter_participant_lbl.place(x=700,y=40) # "Ввод участника:"

    lst_labels = {0: 'Номер', 1: 'Имя', 2: 'Фамилия', 3: 'Представляет'}
    for key in lst_labels:
        lbl_note = ttk.Label(registration_window, text = lst_labels[key] , font=('Arial', 11))
        lbl_note.place(x = 520, y = (ent_ystart + key * ent_ymove) )    # подписи "Номер", "Имя", "Фамилия", "Представляет"

    ent_number.place( x = ent_xstart , y = (ent_ystart + 0 * ent_ymove) ) # поле ввода "Номер"
    ent_name.place( x = ent_xstart , y = (ent_ystart + 1 * ent_ymove) ) # поле ввода "Имя"
    ent_lastname.place( x = ent_xstart , y = (ent_ystart + 2 * ent_ymove) ) # поле ввода "Фамилия"
    ent_locality.place( x = ent_xstart , y = (ent_ystart + 3 * ent_ymove) ) # поле ввода "Представляет"

    btn_registrate.place( x = ent_xstart, y = (ent_ystart + 4 * ent_ymove) ) # кнопка "Зарегистрировать"
    btn_edit.place( x = ent_xstart, y = (ent_ystart + 7 * ent_ymove) ) # кнопка "Редактировать участника"
    btn_finish_registrate.place( x = ent_xstart, y = (ent_ystart + 8 * ent_ymove) ) # кнопка "Завершить регистрацию"
# -------------------------------------------------------------------------------------------------------------------------

# -------------------------------------------------------------------------------------------------------------------------
# СТАРТОВОЕ ПРИВЕТСТВИЕ
start_lbl = ttk.Label(root, text = 'natrium_Na', font=('Arial', 36))
btn_start = ttk.Button(root, text = 'Начать', command = start_registration)
start_lbl.pack(anchor='c', ipady=200)
btn_start.pack(anchor='c')
# -------------------------------------------------------------------------------------------------------------------------


# Размеры шрифтов
small_table_font = 8
medium_table_font = 12
big_table_font = 15

heading_lbl = ttk.Label(registration_window, text='Список участников', font=('Arial', 18)) # заголовок "Список участников"

enter_participant_lbl = ttk.Label(registration_window, text='Ввод участника:', font=('Arial', 16)) # заголовок "Ввод участника"

participants = {}
# -----------ФУНКЦИЯ РЕГИСТРАЦИИ УЧАСТНИКА----------------------------------
def enter_participant():
    number = int( ent_number.get() )
    name = ent_name.get()
    lastname = ent_lastname.get()
    locality = ent_locality.get()
    
    def name_transform(txt):
        txt = txt.lower()
        first_symbol = txt[0].upper()
        final_txt = first_symbol + txt[1:]
        return final_txt
    name = name_transform(name)
    lastname = name_transform(lastname)
    locality = name_transform(locality)
    
    participants[number] = [f'{name} {lastname}', locality]

    counter = 1
    for elem in participants:
        cycle_dict = {0: [counter, 'yellow', 4], 
                      0.4: [elem, 'pink', 5], 
                      0.9: [participants[elem][0], 'blue', 40],
                      4: [participants[elem][1], 'green', 20]}
        for key in cycle_dict:
            lbl = ttk.Label(registration_window, background=cycle_dict[key][1], foreground='black', font=('Arial', 12), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart + key * xmove) , y = (ystart + ymove * counter))
        counter += 1
        
    ent_number.delete(0, END)
    ent_name.delete(0, END)
    ent_lastname.delete(0, END)
    ent_locality.delete(0, END)
# -----------ФУНКЦИЯ РЕГИСТРАЦИИ УЧАСТНИКА---------КОНЕЦ-------------------------

# -----------ФУНКЦИЯ РЕДАКТИРОВАНИЯ УЧАСТНИКА----------------------------------
def edit_participant():
    edin_number_ent = ttk.Entry(registration_window)
    edin_number_ent.place( x = ent_xstart, y = (ent_ystart + 5 * ent_ymove))
# -----------ФУНКЦИЯ РЕДАКТИРОВАНИЯ УЧАСТНИКА---------КОНЕЦ-------------------------

ent_number = ttk.Entry(registration_window) # поле ввода "Номер участника"
ent_name = ttk.Entry(registration_window) # поле ввода "Имя"
ent_lastname = ttk.Entry(registration_window) # поле ввода "Фамилия"
ent_locality = ttk.Entry(registration_window) # поле ввода "Представляет"

btn_registrate = ttk.Button(registration_window, text = 'Зарегистрировать', command = enter_participant)
btn_edit = ttk.Button(registration_window, text = 'Редактировать участника', command = edit_participant)

# -------------------------------------------------------------------------------------------------------------------------
# ЗАПУСК ВТОРОГО ОКНА
qualification_window = ttk.Frame(root, height = 600, width = 1000)

def start_qualification():
    registration_window.destroy()
    qualification_window.pack()
    
    heading_2_lbl.place(x=600, y=10) # "Квалификация"
    participants_list_lbl.place(x=100, y=10) # "Список участников"
    number_participant_lbl.place(x=550,y=60) # "Номер участника"
    throwing_lbl.place(x=550,y=90) # "Броски"
    lbl_throw_seria.place(x=550, y=120) # лейбл "Запись бросков, серия НОМЕР"
    
    number_enter.place(x=700,y=60) # поле ввода "Номер участника"
    throw1_ent.place(x=620,y=90) # поле ввода "Бросок 1"
    throw2_ent.place(x=690,y=90) # поле ввода "Бросок 2"
    throw3_ent.place(x=760,y=90) # поле ввода "Бросок 3"
    
    btn_number.place(x=800,y=60) # кнопка "Выбрать"
    btn_next.place(x=880,y=60) # кнопка "Следующий ?"
    btn_throw_seria.place(x=750,y=120) # кнопка "Записать"
    btn_finish_qualification.place(x=820,y=90) # кнопка "Завершить квалификацию"
    
    # вывод на экран списка участников, прошедшего регистрацию
    counter = 1
    for elem in participants:
        cycle_dict = {  0: [counter, 'yellow', 4], 
                        0.4: [elem, 'pink', 5], 
                        0.9: [participants[elem][0], 'blue', 40],
                        3: [participants[elem][1], 'green', 20]}
        for key in cycle_dict:
            lbl = ttk.Label(qualification_window, background=cycle_dict[key][1], foreground='black', font=('Arial', 8), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart + key * xmove) , y = (ystart + ymove * counter))
        counter += 1

# кнопка с первого окна, которая закрывает 1-е окно и открывает 2-е
btn_finish_registrate = ttk.Button(registration_window, text = 'Завершить регистрацию', command = start_qualification)
# -------------------------------------------------------------------------------------------------------------------------


lst_after_throwing = []


def next_participant():
    lst_participants = list(participants.keys())
    index_participant = 0
    number_enter.insert(index=0, string = f'{lst_participants[index_participant]}')

# -----------ФУНКЦИЯ ВЫБОРА УЧАСТНИКА ДЛЯ БРОСКОВ----------------------------------
qual_number = []
def capture_participant():
    key_number = int( number_enter.get() )
    info_label = ttk.Label(qualification_window, text = f'{key_number}', font=('Arial', 16))
    info_label.place(x=550, y=160)
    name_label = ttk.Label(qualification_window, text = participants[key_number][0], font=('Arial', 30))
    name_label.place(x=610, y=150)
    locality_label = ttk.Label(qualification_window, text = participants[key_number][1], font=('Arial', 18))
    locality_label.place(x=750, y=200)
    qual_number.append(key_number)
    number_enter.delete(0, END)
# -----------ФУНКЦИЯ ВЫБОРА УЧАСТНИКА ДЛЯ БРОСКОВ---------КОНЕЦ-------------------------

xstart2 = 370
xmove2 = 70
ystart2 = 220
ymove2 = 20
padx_value2 = 35
pady_value2 = 10

# -----------ФУНКЦИЯ КНОПКИ ЗАПИСИ БРОСКОВ квалификация----------------------------------
qual_parti = {}
throw_cycle_lst = [1]
def throw_seria():
    key_number = qual_number[0]
    if len(throw_cycle_lst) == 1:
        qual_parti[key_number] = participants[key_number]
        del participants[key_number]
        throw_total = 0
    else: throw_total = qual_parti[key_number][-1][1]
       
    throw_1 = int( throw1_ent.get() )
    throw_2 = int( throw2_ent.get() )
    throw_3 = int( throw3_ent.get() )
    throw_seria = throw_1 + throw_2 + throw_3
    throw_total = throw_total + throw_seria
    seria_ent = (throw_seria, throw_total)
    qual_parti[key_number].append(seria_ent)
    
    qual_parti_sort = dict(sorted(qual_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    qual_parti_lst = list(qual_parti_sort)
    counter_qual = 1
    
    for elem in qual_parti_lst:
        sum_throw = len(qual_parti[elem]) - 2
        cycle_dict = {  0: [counter_qual, 'yellow', 4],         # вывод порядкового номера, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.4: [elem, 'pink', 5],                 # вывод номера участника, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.9: [qual_parti[elem][0], 'blue', 40], # вывод имя-фамилия
                        4: [qual_parti[elem][1], 'green', 20],  # вывод локалити
                        6.5: [qual_parti[elem][2][0], 'pink', 3],    # вывод серия 1
                        6.9: [(qual_parti[elem][3][0] if sum_throw >= 2 else ' '), 'blue', 3],    # вывод серия 2
                        7.3: [(qual_parti[elem][4][0] if sum_throw >= 3 else ' '), 'yellow', 3],    # вывод серия 3
                        7.7: [(qual_parti[elem][5][0] if sum_throw >= 4 else ' '), 'green', 3],    # вывод серия 4
                        8.1: [(qual_parti[elem][6][0] if sum_throw >= 5 else ' '), 'blue', 3],    # вывод серия 5
                        8.5: [qual_parti[elem][-1][1], 'pink', 2],    # вывод серия тотал
                        }
        for key in cycle_dict:
            lbl = ttk.Label(qualification_window, background=cycle_dict[key][1], foreground='black', font=('Arial', 15), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart2 + key * xmove2) , y = (ystart2 + ymove2 * counter_qual))                   
        counter_qual += 1
                
    throw1_ent.delete(0, END)
    throw2_ent.delete(0, END)
    throw3_ent.delete(0, END)
    if len(throw_cycle_lst) == 5:
        qual_number.clear()
        throw_cycle_lst.clear()
        throw_cycle_lst.append(1)
        lst_participants.remove(key_number)
        lst_after_throwing.append(key_number)
    else: throw_cycle_lst.append(1)
# -----------ФУНКЦИЯ КНОПКИ ЗАПИСИ БРОСКОВ квалификация---------КОНЕЦ-------------------------

heading_2_lbl = ttk.Label(qualification_window, text='Квалификация', font=('Arial', 20)) # "Квалификация"
participants_list_lbl = ttk.Label(qualification_window, text='Список участников', font=('Arial', 18)) # "Список участников"
number_participant_lbl = ttk.Label(qualification_window, text='Номер участника', font=('Arial', 13)) # "Номер участника"
throwing_lbl = ttk.Label(qualification_window, text='Броски:', font=('Arial', 13)) # "Броски"
lbl_throw_seria = ttk.Label(qualification_window, text = f'Запись бросков, серия {len(throw_cycle_lst)}:', font=('Arial', 12)) # лейбл "Запись бросков, серия НОМЕР"

number_enter = ttk.Entry(qualification_window, width = 14) # поле ввода "Номер участника"
throw1_ent = ttk.Entry(qualification_window, width = 7) # поле ввода "Бросок 1"
throw2_ent = ttk.Entry(qualification_window, width = 7) # поле ввода "Бросок 2"
throw3_ent = ttk.Entry(qualification_window, width = 7) # поле ввода "Бросок 3"

btn_number = ttk.Button(qualification_window, text = 'Выбрать', command = capture_participant) # кнопка "Выбрать"
btn_next = ttk.Button(qualification_window, text = 'Следующий ?', command = next_participant) # кнопка "Следующий ?"
btn_throw_seria = ttk.Button(qualification_window, text = 'Записать', width = 9, command = throw_seria) # кнопка "Записать"




# -------------------------------------------------------------------------------------------------------------------------
# ЗАПУСК ТРЕТЬЕГО ОКНА
semifinal_window = ttk.Frame(root, height = 600, width = 1000) # рамка для окна полуфинала

semifinalists = {} # словарь, в который войдут стартовые данные с полуфиналистами
def start_semifinal():
    qualification_window.destroy()
    semifinal_window.pack()
    
    heading_3_lbl.place(x=600, y=10) # "ПОЛУФИНАЛ"                              !!!
    semifinalist_list_lbl.place(x=100, y=10) # "Список полуфиналистов"          !!!
    throwing_sf_lbl.place(x=550,y=150) # "Броски"                                !!!
    throw_serial_sf_lbl.place(x=550, y=180) # лейбл "Запись бросков, серия НОМЕР" !!!
    
    throw1_sf_ent.place(x=620,y=150) # поле ввода "Бросок 1"         !!!
    throw2_sf_ent.place(x=690,y=150) # поле ввода "Бросок 2"         !!!
    throw3_sf_ent.place(x=760,y=150) # поле ввода "Бросок 3"         !!!
    
    btn_start_semifinal.place(x=635,y=50) # кнопка "НАЧАТЬ"         !!!
    btn_throw_seria_sf.place(x=750,y=180) # кнопка "Записать"       !!!
    btn_finish_semifinal.place(x=820,y=150) # кнопка "Завершить полуфинал"       !!!
    
    # сортировка и создание словаря 10-ти лучших после квалификации
    qual_parti_sorted = dict(sorted(qual_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    lst_qual_parti = list(qual_parti_sorted)[:10]
    for elem in lst_qual_parti:
        semifinalists[elem] = qual_parti[elem]
    
    # вывод на экран списка квалифицировавшихся участников
    counter = 1
    for elem in semifinalists:
        cycle_dict = {  0: [counter, 'yellow', 4], 
                        0.4: [elem, 'pink', 5], 
                        0.9: [semifinalists[elem][0], 'blue', 40],
                        3: [semifinalists[elem][1], 'green', 20],
                        4.6: [semifinalists[elem][-1][-1], 'pink', 4]}
        for key in cycle_dict:
            lbl = ttk.Label(semifinal_window, background=cycle_dict[key][1], foreground='black', font=('Arial', 8), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart + key * xmove) , y = (ystart + ymove * counter))
        counter += 1

# кнопка со второго окна, которая закрывает 2-е окно и открывает 3-е
btn_finish_qualification = ttk.Button(qualification_window, text = 'Завершить квалификацию', command = start_semifinal) # кнопка "Завершить квалификацию"
# -------------------------------------------------------------------------------------------------------------------------


sequens = [1] # список для контроля текущего участника, по len() определим порядковый номер (т.е. [1, 1, 1] - это 3-ий)
sf_number = [] # здесь будет храниться <номер> участника для взаимосвязи функции button_work_semifinal() с функцией throw_seria_sf()
# -----------ФУНКЦИЯ КНОПКИ "НАЧАТЬ" и "следующий" ПОЛУФИНАЛ----------------------------------
def button_work_semifinal():
    btn_start_semifinal.destroy() # убираем кнопку "НАЧАТЬ"
    
    ###### находим <номер> следующего участника (key_number)
    lst_sf = list(semifinalists.keys())
    sequens_number = len(sequens) - 1
    key_number = lst_sf[sequens_number]
    ###################################
    
    info_label = ttk.Label(semifinal_window, text = f'{key_number}', font=('Arial', 16)) # лейбл с <номером> участника
    info_label.place(x=430, y=60) 
    name_label = ttk.Label(semifinal_window, text = semifinalists[key_number][0], font=('Arial', 30)) # лейбл с <именем-фамилией> участника
    name_label.place(x=480, y=50)
    locality_label = ttk.Label(semifinal_window, text = semifinalists[key_number][1], font=('Arial', 18)) # лейбл с <локалити> участника
    locality_label.place(x=550, y=100)
    score_label = ttk.Label(semifinal_window, text = semifinalists[key_number][-1][-1], background='yellow', font=('Arial', 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    ###### находим целевые <очки> следующего участника (key_number)
    if len(sequens) == 1 : # если участник начинает раунд первым, то у него в цели 0 очков
        points_score = 0
    else: # иначе же находим <номер> лидирующего участника
        sf_parti_sort = dict(sorted(sf_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
        sf_parti_lst = list(sf_parti_sort)
        first_key = sf_parti_lst[0]
        # и вычитаем из <очков> лидера <очки> текущего участника
        points_score = sf_parti[first_key][-1][1] - semifinalists[key_number][-1][1]
    points_label = ttk.Label(semifinal_window, text = points_score, font=('Arial', 18), width = 6)     # лейбл целевого количества очков
    points_label.place(x=910, y=110) 
    goal_throw_sf1_lbl = ttk.Label(semifinal_window, text='до 1-го места', background='yellow', font=('Arial', 12), width = 12) # лейбл "до 1-го места"          !!!
    goal_throw_sf2_lbl = ttk.Label(semifinal_window, text='необходимо', background='yellow', font=('Arial', 12), width = 12) # лейбл "необходимо:"          !!!
    goal_throw_sf1_lbl.place(x=790, y=100)          # лейбл "до 1-го места"          !!!
    goal_throw_sf2_lbl.place(x=790, y=120)          # лейбл "необходимо:"          !!!
    ###################################
    
    sequens.append(1) # в список добавляем единицу, чтобы увеличить len() и контролировать порядок текущего участника
    
    ###### для взаимосвязи с функцией throw_seria_sf() очищаем список sf_number и добавляем в него <номер> текущего участника
    sf_number.clear() 
    sf_number.append(key_number)
    ###################################
    
    btn_next_sf.place(x=850, y=180) # выводим кнопку "следующий"
    
# -----------ФУНКЦИЯ КНОПКИ "НАЧАТЬ" и "следующий" ПОЛУФИНАЛ---------КОНЕЦ-------------------------



sf_parti = {} # словарь для хранения результатов полуфинала
throw_cycle_lst = [1] # список контроля серии бросков с помощью len() от 1 до 5 (т.е. от [1] до [1, 1, 1, 1, 1])
# -----------ФУНКЦИЯ КНОПКИ "ЗАПИСАТЬ" В ПОЛУФИНАЛЕ----------------------------------
def throw_seria_sf():
    key_number = sf_number[0] # сохранённый в списке sf_number <номер> участника заводим в функцию (в key_number)
    
    ###### разбираемся с общей суммой очков текущего участника
    if len(throw_cycle_lst) == 1:   # если это 1-ая серия бросков,  
                                    # то в словарь sf_parti вносим всю информацию об участнике и сумме его очков
        sf_parti[key_number] = semifinalists[key_number]
        throw_total = semifinalists[key_number][-1][1]
    else: # если броски 2ой-5ой серии, то сумму очков берём из sf_parti
        throw_total = sf_parti[key_number][-1][1]
    # из полей ввода соберём все данные о 3-х бросках, найдём их сумму и прибавим к общей сумме
    throw_1 = int( throw1_sf_ent.get() )
    throw_2 = int( throw2_sf_ent.get() )
    throw_3 = int( throw3_sf_ent.get() )
    throw_seria = throw_1 + throw_2 + throw_3
    throw_total = throw_total + throw_seria
    seria_ent = (throw_seria, throw_total) # сделаем кортеж с суммой в серии и общей суммой
    sf_parti[key_number].append(seria_ent) # добавим этот кортеж в список участника по его ключу <номеру>
    ###################################
    
    ###### отсортируем получившийся словарь по общей сумме очков и создадим список sf_parti_lst с отсортированными <номерами> участников 
    sf_parti_sort = dict(sorted(sf_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    sf_parti_lst = list(sf_parti_sort)
    ###################################
    
    ###### лейбл с мониторингом целевых очков для выхода на 1-ое место
    if len(sf_parti_lst) == 1 :         # если это первый полуфиналист (и, соответственно, в списке sf_parti_lst всего один участник),
        points_score = 0                # то у него в целевых очках ноль
    else: # иначе же находим <номер> лидера (first_key)
        first_key = sf_parti_lst[0]
        if first_key == key_number: # если <номер> лидера и есть <номер> текущего участника, то меняем лейбл на "новое преимущество:"
            superiority1_lbl = ttk.Label(semifinal_window, text = 'новое', background='yellow', font=('Arial', 12), width = 12) # лейбл "новое"          !!!
            superiority2_lbl = ttk.Label(semifinal_window, text = 'преимущество:', background='yellow', font=('Arial', 12), width = 12) # лейбл "преимущество:"          !!!
            superiority1_lbl.place(x=790, y=100)  
            superiority2_lbl.place(x=790, y=120)
            second_key = sf_parti_lst[1] # находим <номер> участника на 2-ом месте (second_key)
            points_score = sf_parti_sort[key_number][-1][1] - sf_parti_sort[second_key][-1][1] # и рассчитываем преимущество нового лидера
        else: # если текущий участник не стал новым лидером, то ищем его целевые очки как разницу от очков лидера
            points_score = sf_parti_sort[first_key][-1][1] - sf_parti_sort[key_number][-1][1]
       
    points_label = ttk.Label(semifinal_window, text = points_score, font=('Arial', 18), width = 6)     # число, вывод целевого количества очков
    points_label.place(x=910, y=110)      # число, вывод целевого количества очков
    ###################################
    
    counter_sf = 1
    for elem in sf_parti_lst:
        sum_throw = len(sf_parti[elem]) - 2
        cycle_dict = {  0: [counter_sf, 'yellow', 4],         # вывод порядкового номера, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.4: [elem, 'pink', 5],                 # вывод номера участника, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.9: [sf_parti[elem][0], 'blue', 40], # вывод имя-фамилия
                        4: [sf_parti[elem][1], 'green', 20],  # вывод локалити
                        6.5: [sf_parti[elem][7][0], 'pink', 3],    # вывод серия 1
                        6.9: [(sf_parti[elem][8][0] if sum_throw >= 7 else ' '), 'blue', 3],    # вывод серия 2
                        7.3: [(sf_parti[elem][9][0] if sum_throw >= 8 else ' '), 'yellow', 3],    # вывод серия 3
                        7.7: [(sf_parti[elem][10][0] if sum_throw >= 9 else ' '), 'green', 3],    # вывод серия 4
                        8.1: [(sf_parti[elem][11][0] if sum_throw >= 10 else ' '), 'blue', 3],    # вывод серия 5
                        8.5: [sf_parti[elem][-1][1], 'pink', 2],    # вывод серия тотал
                        }
        for key in cycle_dict:
            lbl = ttk.Label(semifinal_window, background=cycle_dict[key][1], foreground='black', font=('Arial', 15), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart2 + key * xmove2) , y = (ystart2 + ymove2 * counter_sf))                   
        counter_sf += 1
    
    score_label = ttk.Label(semifinal_window, text = sf_parti[key_number][-1][-1], background='yellow', font=('Arial', 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    throw1_sf_ent.delete(0, END)
    throw2_sf_ent.delete(0, END)
    throw3_sf_ent.delete(0, END)
    if len(throw_cycle_lst) == 5:
        sf_number.clear()
        throw_cycle_lst.clear()
        throw_cycle_lst.append(1)
    else: throw_cycle_lst.append(1)
# -----------ФУНКЦИЯ КНОПКИ ЗАПИСАТЬ В ПОЛУФИНАЛЕ---------КОНЕЦ-------------------------

heading_3_lbl = ttk.Label(semifinal_window, text='ПОЛУФИНАЛ', font=('Arial', 20)) # "ПОЛУФИНАЛ"          !!!
semifinalist_list_lbl = ttk.Label(semifinal_window, text='Список полуфиналистов', font=('Arial', 18)) # "Список полуфиналистов"      !!!
throwing_sf_lbl = ttk.Label(semifinal_window, text='Броски:', font=('Arial', 13)) # "Броски"    !!!
throw_serial_sf_lbl = ttk.Label(semifinal_window, text = f'Запись бросков, серия {len(throw_cycle_lst)}:', font=('Arial', 12)) # лейбл "Запись бросков, серия НОМЕР" !!!

throw1_sf_ent = ttk.Entry(semifinal_window, width = 7) # поле ввода "Бросок 1"      !!!
throw2_sf_ent = ttk.Entry(semifinal_window, width = 7) # поле ввода "Бросок 2"      !!!
throw3_sf_ent = ttk.Entry(semifinal_window, width = 7) # поле ввода "Бросок 3"      !!!

btn_start_semifinal = ttk.Button(semifinal_window, text = 'НАЧАТЬ', width = 16, command = button_work_semifinal) # кнопка "НАЧАТЬ" !!!
btn_throw_seria_sf = ttk.Button(semifinal_window, text = 'Записать', width = 9, command = throw_seria_sf) # кнопка "Записать"  !!!
btn_next_sf = ttk.Button(semifinal_window, text = 'следующий', width = 16, command = button_work_semifinal) # кнопка "следующий" !!!


# -------------------------------------------------------------------------------------------------------------------------
# ЗАПУСК ЧЕТВЁРТОГО ОКНА
final_window = ttk.Frame(root, height = 600, width = 1000) # рамка для окна полуфинала

finalists = {} # словарь, в который войдут стартовые данные с полуфиналистами
fnl_start_list = [] # сюда занесём стартовый лист финалистов (в обратном порядке, от 10го места до 1го места)
def start_final():
    semifinal_window.destroy()
    final_window.pack()
    
    heading_4_lbl.place(x=600, y=10) # "ФИНАЛ"                       !!!
    finalist_list_lbl.place(x=100, y=10) # "Список полуфиналистов"          !!!
    throwing_final_lbl.place(x=550,y=150) # "Броски"               !!!
    throw_serial_final_lbl.place(x=550, y=180) # лейбл "Запись бросков, серия НОМЕР"    !!!
    
    throw1_fnl_ent.place(x=620,y=150) # поле ввода "Бросок 1"         !!!
    throw2_fnl_ent.place(x=690,y=150) # поле ввода "Бросок 2"         !!!
    throw3_fnl_ent.place(x=760,y=150) # поле ввода "Бросок 3"         !!!
    
    btn_start_final.place(x=635,y=50) # кнопка "НАЧАТЬ"         !!!
    btn_throw_seria_final.place(x=750,y=180) # кнопка "Записать"       !!!
    
    # сортировка и создание словаря 10-ти лучших после квалификации
    finalists_sorted = dict(sorted(sf_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    lst_fnl_parti = list(finalists_sorted)[:10]
    for elem in lst_fnl_parti:
        finalists[elem] = finalists_sorted[elem]
    
    # стартовый лист финалистов fnl_start_list (в обратном порядке, от 10го места до 1го места)
    for elem in lst_fnl_parti[::-1] :
        fnl_start_list.append(elem)
    
    # вывод на экран списка финалистов
    counter = 1
    for elem in finalists:
        cycle_dict = {  0: [counter, 'yellow', 4], 
                        0.4: [elem, 'pink', 5], 
                        0.9: [finalists[elem][0], 'blue', 40],
                        3: [finalists[elem][1], 'green', 20],
                        4.6: [finalists[elem][-1][-1], 'pink', 4]}
        for key in cycle_dict:
            lbl = ttk.Label(final_window, background=cycle_dict[key][1], foreground='black', font=('Arial', 8), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart + key * xmove) , y = (ystart + ymove * counter))
        counter += 1

# кнопка с третьего окна, которая закрывает 3-е окно и открывает 4-е
btn_finish_semifinal = ttk.Button(semifinal_window, text = 'Завершить полуфинал', command = start_final) # кнопка "Завершить полуфинал" !!!
# -------------------------------------------------------------------------------------------------------------------------


sequens_fnl = [1] # список для контроля текущего участника, по len() определим порядковый номер (т.е. [1, 1, 1] - это 3-ий)
fnl_number = [] # здесь будет храниться <номер> участника для взаимосвязи функции button_work_final() с функцией throw_seria_fnl()
# -----------ФУНКЦИЯ КНОПКИ "НАЧАТЬ" и "следующий" ФИНАЛ----------------------------------
def button_work_final():
    btn_start_final.destroy() # убираем кнопку "НАЧАТЬ"
    
    ###### находим <номер> следующего участника (key_number)   
    sequens_number = len(sequens_fnl) - 1
    key_number = fnl_start_list[sequens_number]
    ###################################
    
    info_label = ttk.Label(final_window, text = f'{key_number}', font=('Arial', 16)) # лейбл с <номером> участника
    info_label.place(x=430, y=60) 
    name_label = ttk.Label(final_window, text = finalists[key_number][0], font=('Arial', 30)) # лейбл с <именем-фамилией> участника
    name_label.place(x=480, y=50)
    locality_label = ttk.Label(final_window, text = finalists[key_number][1], font=('Arial', 18)) # лейбл с <локалити> участника
    locality_label.place(x=550, y=100)
    score_label = ttk.Label(final_window, text = finalists[key_number][-1][-1], background='yellow', font=('Arial', 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    ###### находим целевые <очки> следующего участника (key_number)
    finalists_sort = dict(sorted(finalists.items(), key = lambda x: x[-1][-1][-1], reverse=True))  
    finalists_lst = list(finalists_sort)
    finalists.clear()
    for elem in finalists_lst:
            finalists[elem] = finalists_sort[elem]
    first_key = finalists_lst[0]
    if first_key == key_number: # если <номер> лидера и есть номер текущего участника,
        second_key = finalists_lst[1] # то находим <номер> участника на 2-ом месте (second_key)
        points_score = finalists[key_number][-1][1] - finalists[second_key][-1][1] # и рассчитываем имеющееся преимущество лидера
        goal_throw_fnl1_lbl = ttk.Label(final_window, text='имеющееся', background='yellow', font=('Arial', 12), width = 12) # лейбл "имеющееся"          !!!
        goal_throw_fnl2_lbl = ttk.Label(final_window, text='преимущество', background='yellow', font=('Arial', 12), width = 12) # лейбл "преимущество:"          !!!
        goal_throw_fnl1_lbl.place(x=790, y=100)          # лейбл "имеющееся"          !!!
        goal_throw_fnl2_lbl.place(x=790, y=120)          # лейбл "преимущество:"          !!!
    else: # иначе же вычитаем из <очков> лидера <очки> текущего участника
        points_score = finalists[first_key][-1][1] - finalists[key_number][-1][1]
        goal_throw_fnl1_lbl = ttk.Label(final_window, text='до 1-го места', background='yellow', font=('Arial', 12), width = 12) # лейбл "до 1-го места"          !!!
        goal_throw_fnl2_lbl = ttk.Label(final_window, text='необходимо', background='yellow', font=('Arial', 12), width = 12) # лейбл "необходимо:"          !!!
        goal_throw_fnl1_lbl.place(x=790, y=100)          # лейбл "до 1-го места"          !!!
        goal_throw_fnl2_lbl.place(x=790, y=120)          # лейбл "необходимо:"          !!!
    
    points_label = ttk.Label(final_window, text = points_score, font=('Arial', 18), width = 6)     # лейбл целевого количества очков
    points_label.place(x=910, y=110) 
    
    ###################################
    
    sequens_fnl.append(1) # в список добавляем единицу, чтобы увеличить len() и контролировать порядок текущего участника
    
    ###### для взаимосвязи с функцией throw_seria_fnl() очищаем список fnl_number и добавляем в него <номер> текущего участника
    fnl_number.clear() 
    fnl_number.append(key_number)
    ###################################
    
    btn_next_final.place(x=850, y=180) # выводим кнопку "следующий"

# -----------ФУНКЦИЯ КНОПКИ "НАЧАТЬ" и "следующий" ФИНАЛ---------КОНЕЦ-------------------------


fnl_after_throw = [] # список финалистов, которые начали выполнять свои броски
#throw_cycle_lst = [1] # список контроля серии бросков с помощью len() от 1 до 5 (т.е. от [1] до [1, 1, 1, 1, 1]) УЖЕ СОЗДАН РАНЕЕ
# -----------ФУНКЦИЯ КНОПКИ "ЗАПИСАТЬ" В ФИНАЛЕ----------------------------------
def throw_seria_fnl():
    key_number = fnl_number[0] # сохранённый в списке fnl_number <номер> участника заводим в функцию (в key_number)
    throw_total = finalists[key_number][-1][1]

    # из полей ввода соберём все данные о 3-х бросках, найдём их сумму и прибавим к общей сумме
    throw_1 = int( throw1_fnl_ent.get() )
    throw_2 = int( throw2_fnl_ent.get() )
    throw_3 = int( throw3_fnl_ent.get() )
    throw_seria = throw_1 + throw_2 + throw_3
    throw_total = throw_total + throw_seria
    seria_ent = (throw_seria, throw_total) # сделаем кортеж с суммой в серии и общей суммой
    finalists[key_number].append(seria_ent) # добавим этот кортеж в список участника по его ключу <номеру>
    ###################################
    
    ###### отсортируем получившийся словарь по общей сумме очков и создадим список finalists_lst с отсортированными <номерами> участников 
    finalists_sort = dict(sorted(finalists.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    finalists_lst = list(finalists_sort)
    finalists.clear()
    for elem in finalists_lst:
            finalists[elem] = finalists_sort[elem]
    ###################################
    
    ###### лейбл с мониторингом целевых очков для выхода на 1-ое место
    first_key = finalists_lst[0]
    if first_key == key_number: # если <номер> лидера и есть <номер> текущего участника, то меняем лейбл на "новое преимущество:"
        superiority1_lbl = ttk.Label(final_window, text = 'новое', background='yellow', font=('Arial', 12), width = 12) # лейбл "новое"          !!!
        superiority2_lbl = ttk.Label(final_window, text = 'преимущество:', background='yellow', font=('Arial', 12), width = 12) # лейбл "преимущество:"          !!!
        superiority1_lbl.place(x=790, y=100)  
        superiority2_lbl.place(x=790, y=120)
        second_key = finalists_lst[1] # находим <номер> участника на 2-ом месте (second_key)
        points_score = finalists[key_number][-1][1] - finalists[second_key][-1][1] # и рассчитываем преимущество нового лидера
    else: # если текущий участник не стал новым лидером, то ищем его целевые очки как разницу от очков лидера
        points_score = finalists[first_key][-1][1] - finalists[key_number][-1][1]
       
    points_label = ttk.Label(final_window, text = points_score, font=('Arial', 18), width = 6)     # число, вывод целевого количества очков
    points_label.place(x=910, y=110)      # число, вывод целевого количества очков
    ###################################
    
    counter_fnl = 1
    fnl_after_throw.append(key_number)
    for elem in finalists_lst:
        if elem in fnl_after_throw:
            sum_throw = len(finalists[elem]) - 2
            cycle_dict = {  0: [counter_fnl, 'yellow', 4],         # вывод порядкового номера, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                            0.4: [elem, 'pink', 5],                 # вывод номера участника, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                            0.9: [finalists[elem][0], 'blue', 40], # вывод имя-фамилия
                            4: [finalists[elem][1], 'green', 20],  # вывод локалити
                            6.5: [(finalists[elem][12][0] if sum_throw >= 11 else ' '), 'pink', 3],    # вывод серия 1
                            6.9: [(finalists[elem][13][0] if sum_throw >= 12 else ' '), 'blue', 3],    # вывод серия 2
                            7.3: [(finalists[elem][14][0] if sum_throw >= 13 else ' '), 'yellow', 3],    # вывод серия 3
                            7.7: [(finalists[elem][15][0] if sum_throw >= 14 else ' '), 'green', 3],    # вывод серия 4
                            8.1: [(finalists[elem][16][0] if sum_throw >= 15 else ' '), 'blue', 3],    # вывод серия 5
                            8.5: [finalists[elem][-1][1], 'pink', 2],    # вывод серия тотал
                            }
            for key in cycle_dict:
                lbl = ttk.Label(final_window, background=cycle_dict[key][1], foreground='black', font=('Arial', 15), width = cycle_dict[key][2])
                lbl['text'] = cycle_dict[key][0]
                lbl.place( x = (xstart2 + key * xmove2) , y = (ystart2 + ymove2 * counter_fnl))                   
            counter_fnl += 1
    
    score_label = ttk.Label(final_window, text = finalists[key_number][-1][-1], background='yellow', font=('Arial', 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    throw1_fnl_ent.delete(0, END)
    throw2_fnl_ent.delete(0, END)
    throw3_fnl_ent.delete(0, END)
    if len(throw_cycle_lst) == 5:
        fnl_number.clear()
        throw_cycle_lst.clear()
        throw_cycle_lst.append(1)
    else: throw_cycle_lst.append(1)
# -----------ФУНКЦИЯ КНОПКИ ЗАПИСАТЬ В ФИНАЛЕ---------КОНЕЦ-------------------------

heading_4_lbl = ttk.Label(final_window, text='ФИНАЛ', font=('Arial', 20)) # "ФИНАЛ"          !!!
finalist_list_lbl = ttk.Label(final_window, text='Список финалистов', font=('Arial', 18)) # "Список финалистов"      !!!
throwing_final_lbl = ttk.Label(final_window, text='Броски:', font=('Arial', 13)) # "Броски"         !!!
throw_serial_final_lbl = ttk.Label(final_window, text = f'Запись бросков, серия {len(throw_cycle_lst)}:', font=('Arial', 12)) # лейбл "Запись бросков, серия НОМЕР" !!!

throw1_fnl_ent = ttk.Entry(final_window, width = 7) # поле ввода "Бросок 1"      !!!
throw2_fnl_ent = ttk.Entry(final_window, width = 7) # поле ввода "Бросок 2"      !!!
throw3_fnl_ent = ttk.Entry(final_window, width = 7) # поле ввода "Бросок 3"      !!!

btn_start_final = ttk.Button(final_window, text = 'НАЧАТЬ', width = 16, command = button_work_final) # кнопка "НАЧАТЬ" !!!
btn_throw_seria_final = ttk.Button(final_window, text = 'Записать', width = 9, command = throw_seria_fnl) # кнопка "Записать"  !!!
btn_next_final = ttk.Button(final_window, text = 'следующий', width = 16, command = button_work_final) # кнопка "следующий"    !!!


root.mainloop()

In [344]:
# РАБОТА НАД ВИЗУАЛОМ В БЕТА-ВЕРСИИ
from tkinter import *
# используемые цвета
base_color = 'LightYellow'  # базовый цвет
active_color = 'pink'     # активный цвет
first_color = 'gold'        # цвет 1-го места
second_color = 'silver'     # цвет 2-го места
third_color = 'peru'        # цвет 3-го места

# шрифты
small_table_font = 8
medium_table_font = 12
big_table_font = 15
font_name = 'Helvetica'

root = Tk()
root.geometry('1020x600')
root.configure(background=base_color)
root.title('Соревнования по дартс')
#root.attributes('-fullscreen', True)

# базовые координаты и смещения
xstart = 10         # старт по X
ystart = 40         # старт по Y

xmove = 70          # сдвиг по X
ymove = 20          # сдвиг по Y

padx_value = 35
pady_value = 10

ent_xstart = 700    # cтарт по X для Entry
ent_ystart = 80    # cтарт по Y для Entry
ent_ymove = 35      # сдвиг для Entry



# -------------------------------------------------------------------------------------------------------------------------
# ЗАПУСК ПЕРВОГО ОКНА (ПОСЛЕ СТАРТОВОГО ПРИВЕТСТВИЯ)
registration_window = Frame(root, background=base_color, height = 600, width = 1020)

def start_registration():
    ###### убираем приветствия и выводим Frame-квалификацию
    start_lbl.destroy()
    btn_start.destroy()
    registration_window.pack()
    #####################################
    
    ###### располагаем виджеты для квалификации
    heading_lbl.place(x=100, y=10) # "Список участников"
    enter_participant_lbl.place(x=700,y=40) # "Ввод участника:"

    lst_labels = {0: 'Номер', 1: 'Имя', 2: 'Фамилия', 3: 'Представляет'}
    for key in lst_labels:
        lbl_note = Label(registration_window, text = lst_labels[key],  background=base_color, font=(font_name, 11))
        lbl_note.place(x = 520, y = (ent_ystart + key * ent_ymove) )    # подписи "Номер", "Имя", "Фамилия", "Представляет"

    ent_number.place( x = ent_xstart , y = (ent_ystart + 0 * ent_ymove) ) # поле ввода "Номер"
    ent_name.place( x = ent_xstart , y = (ent_ystart + 1 * ent_ymove) ) # поле ввода "Имя"
    ent_lastname.place( x = ent_xstart , y = (ent_ystart + 2 * ent_ymove) ) # поле ввода "Фамилия"
    ent_locality.place( x = ent_xstart , y = (ent_ystart + 3 * ent_ymove) ) # поле ввода "Представляет"

    btn_registrate.place( x = ent_xstart, y = (ent_ystart + 4 * ent_ymove) ) # кнопка "Зарегистрировать"
    btn_edit.place( x = ent_xstart, y = (ent_ystart + 7 * ent_ymove) ) # кнопка "Редактировать участника"
    btn_finish_registrate.place( x = ent_xstart, y = (ent_ystart + 8 * ent_ymove) ) # кнопка "Завершить регистрацию"
    #########################################
# -------------------------------------------------------------------------------------------------------------------------

# -------------------------------------------------------------------------------------------------------------------------
# СТАРТОВОЕ ПРИВЕТСТВИЕ
start_lbl = Label(root, text = 'natrium_Na', background=base_color, font=(font_name, 36))
btn_start = Button(root, text = 'НАЧАТЬ', background=base_color, command = start_registration)
start_lbl.pack(anchor='c', ipady=200)
btn_start.pack(anchor='c')
# -------------------------------------------------------------------------------------------------------------------------


heading_lbl = Label(registration_window, text='Список участников', background=base_color, font=(font_name, 18)) # заголовок "Список участников"

enter_participant_lbl = Label(registration_window, text='Ввод участника:', background=base_color, font=(font_name, 16)) # заголовок "Ввод участника"

participants = {} # словарь для хранения информации об участниках в формате {номер: ['Имя Фамилия', 'Локалити'], номер: ['Имя Фамилия', 'Локалити']}
# -----------ФУНКЦИЯ РЕГИСТРАЦИИ УЧАСТНИКА----------------------------------
def enter_participant():
    ###### записываем данные из Entry
    number = int( ent_number.get() )
    name = ent_name.get()
    lastname = ent_lastname.get()
    locality = ent_locality.get()
    # и трасформируем буквы имени-фамилии и локалити в заглавную и строчные
    def name_transform(txt):
        txt = txt.lower()
        first_symbol = txt[0].upper()
        final_txt = first_symbol + txt[1:]
        return final_txt
    name = name_transform(name)
    lastname = name_transform(lastname)
    locality = name_transform(locality)
    # заносим данные об участнике в словарь participants
    participants[number] = [f'{name} {lastname}', locality]
    #############################################
    ###### теперь выводим информацию о всех зарегистрированных участниках в левую часть экрана
    counter = 1
    for elem in participants:
        cycle_dict = {0: [f'{counter}.', base_color, 4], # 
                      0.6: [elem, base_color, 6], 
                      1.4: [participants[elem][0], base_color, 20],
                      4.1: [participants[elem][1], base_color, 20]}
        for key in cycle_dict:
            lbl = Label(registration_window, background=cycle_dict[key][1], foreground='black', font=(font_name, 12), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart + key * xmove) , y = (ystart + ymove * counter))
        counter += 1
        
    ent_number.delete(0, END)
    ent_name.delete(0, END)
    ent_lastname.delete(0, END)
    ent_locality.delete(0, END)
# -----------ФУНКЦИЯ РЕГИСТРАЦИИ УЧАСТНИКА---------КОНЕЦ-------------------------

# -----------ФУНКЦИЯ РЕДАКТИРОВАНИЯ УЧАСТНИКА----------------------------------
def edit_participant():
    edin_number_ent = Entry(registration_window)
    edin_number_ent.place( x = ent_xstart, y = (ent_ystart + 5 * ent_ymove))
# -----------ФУНКЦИЯ РЕДАКТИРОВАНИЯ УЧАСТНИКА---------КОНЕЦ-------------------------

ent_number = Entry(registration_window) # поле ввода "Номер участника"
ent_name = Entry(registration_window) # поле ввода "Имя"
ent_lastname = Entry(registration_window) # поле ввода "Фамилия"
ent_locality = Entry(registration_window) # поле ввода "Представляет"

btn_registrate = Button(registration_window, text = 'Зарегистрировать', background=base_color, command = enter_participant)
btn_edit = Button(registration_window, text = 'Редактировать участника', background=base_color, command = edit_participant)

# -------------------------------------------------------------------------------------------------------------------------
# ЗАПУСК ВТОРОГО ОКНА
qualification_window = Frame(root, height = 600, width = 1020, background=base_color)

def start_qualification():
    registration_window.destroy()
    qualification_window.pack()
    
    heading_2_lbl.place(x=600, y=10) # "Квалификация"
    participants_list_lbl.place(x=100, y=10) # "Список участников"
    number_participant_lbl.place(x=550,y=60) # "Номер участника"
    throwing_lbl.place(x=550,y=90) # "Броски"
    lbl_throw_seria.place(x=550, y=120) # лейбл "Запись бросков, серия НОМЕР"
    
    number_enter.place(x=700,y=60) # поле ввода "Номер участника"
    throw1_ent.place(x=620,y=90) # поле ввода "Бросок 1"
    throw2_ent.place(x=690,y=90) # поле ввода "Бросок 2"
    throw3_ent.place(x=760,y=90) # поле ввода "Бросок 3"
    
    btn_number.place(x=800,y=60) # кнопка "Выбрать"
    btn_next.place(x=880,y=60) # кнопка "Следующий ?"
    btn_throw_seria.place(x=750,y=120) # кнопка "Записать"
    btn_finish_qualification.place(x=820,y=90) # кнопка "Завершить квалификацию"
    
    # вывод на экран списка участников, прошедшего регистрацию
    counter = 1
    for elem in participants:
        cycle_dict = {  0: [f'{counter}.', base_color, 4],    # вывод порядкового номера, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.6: [elem, base_color, 6],     # вывод номера участника, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        1.4: [participants[elem][0], base_color, 20],   # вывод имя-фамилия
                        4.1: [participants[elem][1], base_color, 20]}     # вывод локалити
        for key in cycle_dict:
            lbl = Label(qualification_window, background=cycle_dict[key][1], foreground='black', font=(font_name, 8), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart + key * xmove) , y = (ystart + ymove * counter))
        counter += 1

# кнопка с первого окна, которая закрывает 1-е окно и открывает 2-е
btn_finish_registrate = Button(registration_window, text = 'Завершить регистрацию', background=base_color, command = start_qualification)
# -------------------------------------------------------------------------------------------------------------------------


lst_after_throwing = []


def next_participant():
    lst_participants = list(participants.keys())
    index_participant = 0
    number_enter.insert(index=0, string = f'{lst_participants[index_participant]}')

# -----------ФУНКЦИЯ ВЫБОРА УЧАСТНИКА ДЛЯ БРОСКОВ----------------------------------
qual_number = []
def capture_participant():
    key_number = int( number_enter.get() )
    info_label = Label(qualification_window, text = f'{key_number}', background=base_color, font=(font_name, 16))
    info_label.place(x=550, y=160)
    name_label = Label(qualification_window, text = participants[key_number][0], background=base_color, font=(font_name, 30))
    name_label.place(x=610, y=150)
    locality_label = Label(qualification_window, text = participants[key_number][1], background=base_color, font=(font_name, 18))
    locality_label.place(x=750, y=200)
    qual_number.append(key_number)
    number_enter.delete(0, END)
# -----------ФУНКЦИЯ ВЫБОРА УЧАСТНИКА ДЛЯ БРОСКОВ---------КОНЕЦ-------------------------

xstart2 = 370
xmove2 = 70
ystart2 = 220
ymove2 = 20
padx_value2 = 35
pady_value2 = 10

# -----------ФУНКЦИЯ КНОПКИ ЗАПИСИ БРОСКОВ квалификация----------------------------------
qual_parti = {}
throw_cycle_lst = [1]
def throw_seria():
    key_number = qual_number[0]
    if len(throw_cycle_lst) == 1:
        qual_parti[key_number] = participants[key_number]
        del participants[key_number]
        throw_total = 0
    else: throw_total = qual_parti[key_number][-1][1]
       
    throw_1 = int( throw1_ent.get() )
    throw_2 = int( throw2_ent.get() )
    throw_3 = int( throw3_ent.get() )
    throw_seria = throw_1 + throw_2 + throw_3
    throw_total = throw_total + throw_seria
    seria_ent = (throw_seria, throw_total)
    qual_parti[key_number].append(seria_ent)
    
    qual_parti_sort = dict(sorted(qual_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    qual_parti_lst = list(qual_parti_sort)
    counter_qual = 1
    
    for elem in qual_parti_lst:
        if elem == key_number: parti_color = base_color
        else: parti_color = active_color
        sum_throw = len(qual_parti[elem]) - 2
        cycle_dict = {  0: [f'{counter_qual}.', parti_color, 4],         # вывод порядкового номера, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.4: [elem, parti_color, 5],                 # вывод номера участника, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.9: [qual_parti[elem][0], parti_color, 40], # вывод имя-фамилия
                        4: [qual_parti[elem][1], parti_color, 20],  # вывод локалити
                        6.5: [qual_parti[elem][2][0], parti_color, 3],    # вывод серия 1
                        6.9: [(qual_parti[elem][3][0] if sum_throw >= 2 else ' '), parti_color, 3],    # вывод серия 2
                        7.3: [(qual_parti[elem][4][0] if sum_throw >= 3 else ' '), parti_color, 3],    # вывод серия 3
                        7.7: [(qual_parti[elem][5][0] if sum_throw >= 4 else ' '), parti_color, 3],    # вывод серия 4
                        8.1: [(qual_parti[elem][6][0] if sum_throw >= 5 else ' '), parti_color, 3],    # вывод серия 5
                        8.5: [qual_parti[elem][-1][1], parti_color, 2],    # вывод серия тотал
                        }
        for key in cycle_dict:
            lbl = Label(qualification_window, background=cycle_dict[key][1], foreground='black', font=(font_name, 15), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart2 + key * xmove2) , y = (ystart2 + ymove2 * counter_qual))                   
        counter_qual += 1
                
    throw1_ent.delete(0, END)
    throw2_ent.delete(0, END)
    throw3_ent.delete(0, END)
    if len(throw_cycle_lst) == 5:
        qual_number.clear()
        throw_cycle_lst.clear()
        throw_cycle_lst.append(1)
        lst_participants.remove(key_number)
        lst_after_throwing.append(key_number)
    else: throw_cycle_lst.append(1)
# -----------ФУНКЦИЯ КНОПКИ ЗАПИСИ БРОСКОВ квалификация---------КОНЕЦ-------------------------

heading_2_lbl = Label(qualification_window, text='Квалификация', background=base_color, font=(font_name, 20)) # "Квалификация"
participants_list_lbl = Label(qualification_window, text='Список участников', background=base_color, font=(font_name, 18)) # "Список участников"
number_participant_lbl = Label(qualification_window, text='Номер участника', background=base_color, font=(font_name, 13)) # "Номер участника"
throwing_lbl = Label(qualification_window, text='Броски:', background=base_color, font=(font_name, 13)) # "Броски"
lbl_throw_seria = Label(qualification_window, text = f'Запись бросков, серия {len(throw_cycle_lst)}:', background=base_color, font=(font_name, 12)) # лейбл "Запись бросков, серия НОМЕР"

number_enter = Entry(qualification_window, width = 14) # поле ввода "Номер участника"
throw1_ent = Entry(qualification_window, width = 7) # поле ввода "Бросок 1"
throw2_ent = Entry(qualification_window, width = 7) # поле ввода "Бросок 2"
throw3_ent = Entry(qualification_window, width = 7) # поле ввода "Бросок 3"

btn_number = Button(qualification_window, text = 'Выбрать', background=base_color, command = capture_participant) # кнопка "Выбрать"
btn_next = Button(qualification_window, text = 'Следующий ?', background=base_color, command = next_participant) # кнопка "Следующий ?"
btn_throw_seria = Button(qualification_window, text = 'Записать', background=base_color, width = 9, command = throw_seria) # кнопка "Записать"




# -------------------------------------------------------------------------------------------------------------------------
# ЗАПУСК ТРЕТЬЕГО ОКНА
semifinal_window = Frame(root, height = 600, width = 1020, background=base_color) # рамка для окна полуфинала

semifinalists = {} # словарь, в который войдут стартовые данные с полуфиналистами
def start_semifinal():
    qualification_window.destroy()
    semifinal_window.pack()
    
    heading_3_lbl.place(x=600, y=10) # "ПОЛУФИНАЛ"                              !!!
    semifinalist_list_lbl.place(x=100, y=10) # "Список полуфиналистов"          !!!
    throwing_sf_lbl.place(x=550,y=150) # "Броски"                                !!!
    throw_serial_sf_lbl.place(x=550, y=180) # лейбл "Запись бросков, серия НОМЕР" !!!
    
    throw1_sf_ent.place(x=620,y=150) # поле ввода "Бросок 1"         !!!
    throw2_sf_ent.place(x=690,y=150) # поле ввода "Бросок 2"         !!!
    throw3_sf_ent.place(x=760,y=150) # поле ввода "Бросок 3"         !!!
    
    btn_start_semifinal.place(x=635,y=50) # кнопка "НАЧАТЬ"         !!!
    btn_throw_seria_sf.place(x=750,y=180) # кнопка "Записать"       !!!
    btn_finish_semifinal.place(x=820,y=150) # кнопка "Завершить полуфинал"       !!!
    
    # сортировка и создание словаря 10-ти лучших после квалификации
    qual_parti_sorted = dict(sorted(qual_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    lst_qual_parti = list(qual_parti_sorted)[:10]
    for elem in lst_qual_parti:
        semifinalists[elem] = qual_parti[elem]
    
    # вывод на экран списка квалифицировавшихся участников
    counter = 1
    for elem in semifinalists:
        cycle_dict = {  0: [f'{counter}.', base_color, 4], 
                        0.4: [elem, base_color, 5], 
                        0.9: [semifinalists[elem][0], base_color, 40],
                        3: [semifinalists[elem][1], base_color, 20],
                        4.6: [semifinalists[elem][-1][-1], base_color, 4]}
        for key in cycle_dict:
            lbl = Label(semifinal_window, background=cycle_dict[key][1], foreground='black', font=(font_name, 8), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart + key * xmove) , y = (ystart + ymove * counter))
        counter += 1

# кнопка со второго окна, которая закрывает 2-е окно и открывает 3-е
btn_finish_qualification = Button(qualification_window, text = 'Завершить квалификацию', background=base_color, command = start_semifinal) # кнопка "Завершить квалификацию"
# -------------------------------------------------------------------------------------------------------------------------


sequens = [1] # список для контроля текущего участника, по len() определим порядковый номер (т.е. [1, 1, 1] - это 3-ий)
sf_number = [] # здесь будет храниться <номер> участника для взаимосвязи функции button_work_semifinal() с функцией throw_seria_sf()
# -----------ФУНКЦИЯ КНОПКИ "НАЧАТЬ" и "следующий" ПОЛУФИНАЛ----------------------------------
def button_work_semifinal():
    btn_start_semifinal.destroy() # убираем кнопку "НАЧАТЬ"
    
    ###### находим <номер> следующего участника (key_number)
    lst_sf = list(semifinalists.keys())
    sequens_number = len(sequens) - 1
    key_number = lst_sf[sequens_number]
    ###################################
    
    info_label = Label(semifinal_window, text = f'{key_number}', background=base_color, font=(font_name, 16)) # лейбл с <номером> участника
    info_label.place(x=430, y=60) 
    name_label = Label(semifinal_window, text = semifinalists[key_number][0], background=base_color, font=(font_name, 30)) # лейбл с <именем-фамилией> участника
    name_label.place(x=480, y=50)
    locality_label = Label(semifinal_window, text = semifinalists[key_number][1], background=base_color, font=(font_name, 18)) # лейбл с <локалити> участника
    locality_label.place(x=550, y=100)
    score_label = Label(semifinal_window, text = semifinalists[key_number][-1][-1], background=base_color, font=(font_name, 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    ###### находим целевые <очки> следующего участника (key_number)
    if len(sequens) == 1 : # если участник начинает раунд первым, то у него в цели 0 очков
        points_score = 0
    else: # иначе же находим <номер> лидирующего участника
        sf_parti_sort = dict(sorted(sf_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
        sf_parti_lst = list(sf_parti_sort)
        first_key = sf_parti_lst[0]
        # и вычитаем из <очков> лидера <очки> текущего участника
        points_score = sf_parti[first_key][-1][1] - semifinalists[key_number][-1][1]
    points_label = Label(semifinal_window, text = points_score, background=base_color, font=(font_name, 18), width = 6)     # лейбл целевого количества очков
    points_label.place(x=910, y=110) 
    goal_throw_sf1_lbl = Label(semifinal_window, text='до 1-го места', background=base_color, font=(font_name, 12), width = 12) # лейбл "до 1-го места"          !!!
    goal_throw_sf2_lbl = Label(semifinal_window, text='необходимо', background=base_color, font=(font_name, 12), width = 12) # лейбл "необходимо:"          !!!
    goal_throw_sf1_lbl.place(x=790, y=100)          # лейбл "до 1-го места"          !!!
    goal_throw_sf2_lbl.place(x=790, y=120)          # лейбл "необходимо:"          !!!
    ###################################
    
    sequens.append(1) # в список добавляем единицу, чтобы увеличить len() и контролировать порядок текущего участника
    
    ###### для взаимосвязи с функцией throw_seria_sf() очищаем список sf_number и добавляем в него <номер> текущего участника
    sf_number.clear() 
    sf_number.append(key_number)
    ###################################
    
    btn_next_sf.place(x=850, y=180) # выводим кнопку "следующий"
    
# -----------ФУНКЦИЯ КНОПКИ "НАЧАТЬ" и "следующий" ПОЛУФИНАЛ---------КОНЕЦ-------------------------



sf_parti = {} # словарь для хранения результатов полуфинала
throw_cycle_lst = [1] # список контроля серии бросков с помощью len() от 1 до 5 (т.е. от [1] до [1, 1, 1, 1, 1])
# -----------ФУНКЦИЯ КНОПКИ "ЗАПИСАТЬ" В ПОЛУФИНАЛЕ----------------------------------
def throw_seria_sf():
    key_number = sf_number[0] # сохранённый в списке sf_number <номер> участника заводим в функцию (в key_number)
    
    ###### разбираемся с общей суммой очков текущего участника
    if len(throw_cycle_lst) == 1:   # если это 1-ая серия бросков,  
                                    # то в словарь sf_parti вносим всю информацию об участнике и сумме его очков
        sf_parti[key_number] = semifinalists[key_number]
        throw_total = semifinalists[key_number][-1][1]
    else: # если броски 2ой-5ой серии, то сумму очков берём из sf_parti
        throw_total = sf_parti[key_number][-1][1]
    # из полей ввода соберём все данные о 3-х бросках, найдём их сумму и прибавим к общей сумме
    throw_1 = int( throw1_sf_ent.get() )
    throw_2 = int( throw2_sf_ent.get() )
    throw_3 = int( throw3_sf_ent.get() )
    throw_seria = throw_1 + throw_2 + throw_3
    throw_total = throw_total + throw_seria
    seria_ent = (throw_seria, throw_total) # сделаем кортеж с суммой в серии и общей суммой
    sf_parti[key_number].append(seria_ent) # добавим этот кортеж в список участника по его ключу <номеру>
    ###################################
    
    ###### отсортируем получившийся словарь по общей сумме очков и создадим список sf_parti_lst с отсортированными <номерами> участников 
    sf_parti_sort = dict(sorted(sf_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    sf_parti_lst = list(sf_parti_sort)
    ###################################
    
    ###### лейбл с мониторингом целевых очков для выхода на 1-ое место
    if len(sf_parti_lst) == 1 :         # если это первый полуфиналист (и, соответственно, в списке sf_parti_lst всего один участник),
        points_score = 0                # то у него в целевых очках ноль
    else: # иначе же находим <номер> лидера (first_key)
        first_key = sf_parti_lst[0]
        if first_key == key_number: # если <номер> лидера и есть <номер> текущего участника, то меняем лейбл на "новое преимущество:"
            superiority1_lbl = Label(semifinal_window, text = 'новое', background=base_color, font=(font_name, 12), width = 12) # лейбл "новое"          !!!
            superiority2_lbl = Label(semifinal_window, text = 'преимущество:', background=base_color, font=(font_name, 12), width = 12) # лейбл "преимущество:"          !!!
            superiority1_lbl.place(x=790, y=100)  
            superiority2_lbl.place(x=790, y=120)
            second_key = sf_parti_lst[1] # находим <номер> участника на 2-ом месте (second_key)
            points_score = sf_parti_sort[key_number][-1][1] - sf_parti_sort[second_key][-1][1] # и рассчитываем преимущество нового лидера
        else: # если текущий участник не стал новым лидером, то ищем его целевые очки как разницу от очков лидера
            points_score = sf_parti_sort[first_key][-1][1] - sf_parti_sort[key_number][-1][1]
       
    points_label = Label(semifinal_window, text = points_score, background=base_color, font=(font_name, 18), width = 6)     # число, вывод целевого количества очков
    points_label.place(x=910, y=110)      # число, вывод целевого количества очков
    ###################################
    
    counter_sf = 1
    for elem in sf_parti_lst:
        if elem == key_number: parti_color = base_color
        else: parti_color = active_color
        sum_throw = len(sf_parti[elem]) - 2
        cycle_dict = {  0: [f'{counter_sf}.', parti_color, 4],         # вывод порядкового номера, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.4: [elem, parti_color, 5],                 # вывод номера участника, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.9: [sf_parti[elem][0], parti_color, 40], # вывод имя-фамилия
                        4: [sf_parti[elem][1], parti_color, 20],  # вывод локалити
                        6.5: [sf_parti[elem][7][0], parti_color, 3],    # вывод серия 1
                        6.9: [(sf_parti[elem][8][0] if sum_throw >= 7 else ' '), parti_color, 3],    # вывод серия 2
                        7.3: [(sf_parti[elem][9][0] if sum_throw >= 8 else ' '), parti_color, 3],    # вывод серия 3
                        7.7: [(sf_parti[elem][10][0] if sum_throw >= 9 else ' '), parti_color, 3],    # вывод серия 4
                        8.1: [(sf_parti[elem][11][0] if sum_throw >= 10 else ' '), parti_color, 3],    # вывод серия 5
                        8.5: [sf_parti[elem][-1][1], parti_color, 2],    # вывод серия тотал
                        }
        for key in cycle_dict:
            lbl = Label(semifinal_window, background=cycle_dict[key][1], foreground='black', font=(font_name, 15), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart2 + key * xmove2) , y = (ystart2 + ymove2 * counter_sf))                   
        counter_sf += 1
    
    score_label = Label(semifinal_window, text = sf_parti[key_number][-1][-1], background=base_color, font=(font_name, 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    throw1_sf_ent.delete(0, END)
    throw2_sf_ent.delete(0, END)
    throw3_sf_ent.delete(0, END)
    if len(throw_cycle_lst) == 5:
        sf_number.clear()
        throw_cycle_lst.clear()
        throw_cycle_lst.append(1)
    else: throw_cycle_lst.append(1)
# -----------ФУНКЦИЯ КНОПКИ ЗАПИСАТЬ В ПОЛУФИНАЛЕ---------КОНЕЦ-------------------------

heading_3_lbl = Label(semifinal_window, text='ПОЛУФИНАЛ', background=base_color, font=(font_name, 20)) # "ПОЛУФИНАЛ"          !!!
semifinalist_list_lbl = Label(semifinal_window, text='Список полуфиналистов', background=base_color, font=('Arial', 18)) # "Список полуфиналистов"      !!!
throwing_sf_lbl = Label(semifinal_window, text='Броски:', background=base_color, font=(font_name, 13)) # "Броски"    !!!
throw_serial_sf_lbl = Label(semifinal_window, text = f'Запись бросков, серия {len(throw_cycle_lst)}:', background=base_color, font=(font_name, 12)) # лейбл "Запись бросков, серия НОМЕР" !!!

throw1_sf_ent = Entry(semifinal_window, width = 7) # поле ввода "Бросок 1"      !!!
throw2_sf_ent = Entry(semifinal_window, width = 7) # поле ввода "Бросок 2"      !!!
throw3_sf_ent = Entry(semifinal_window, width = 7) # поле ввода "Бросок 3"      !!!

btn_start_semifinal = Button(semifinal_window, text = 'НАЧАТЬ', background=base_color, width = 16, command = button_work_semifinal) # кнопка "НАЧАТЬ" !!!
btn_throw_seria_sf = Button(semifinal_window, text = 'Записать', background=base_color, width = 9, command = throw_seria_sf) # кнопка "Записать"  !!!
btn_next_sf = Button(semifinal_window, text = 'следующий', background=base_color, width = 16, command = button_work_semifinal) # кнопка "следующий" !!!


# -------------------------------------------------------------------------------------------------------------------------
# ЗАПУСК ЧЕТВЁРТОГО ОКНА
final_window = Frame(root, height = 600, width = 1020, background=base_color) # рамка для окна полуфинала

finalists = {} # словарь, в который войдут стартовые данные с полуфиналистами
fnl_start_list = [] # сюда занесём стартовый лист финалистов (в обратном порядке, от 10го места до 1го места)
def start_final():
    semifinal_window.destroy()
    final_window.pack()
    
    heading_4_lbl.place(x=600, y=10) # "ФИНАЛ"                       !!!
    finalist_list_lbl.place(x=100, y=10) # "Список полуфиналистов"          !!!
    throwing_final_lbl.place(x=550,y=150) # "Броски"               !!!
    throw_serial_final_lbl.place(x=550, y=180) # лейбл "Запись бросков, серия НОМЕР"    !!!
    
    throw1_fnl_ent.place(x=620,y=150) # поле ввода "Бросок 1"         !!!
    throw2_fnl_ent.place(x=690,y=150) # поле ввода "Бросок 2"         !!!
    throw3_fnl_ent.place(x=760,y=150) # поле ввода "Бросок 3"         !!!
    
    btn_start_final.place(x=635,y=50) # кнопка "НАЧАТЬ"         !!!
    btn_throw_seria_final.place(x=750,y=180) # кнопка "Записать"       !!!
    
    # сортировка и создание словаря 10-ти лучших после квалификации
    finalists_sorted = dict(sorted(sf_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    lst_fnl_parti = list(finalists_sorted)[:10]
    for elem in lst_fnl_parti:
        finalists[elem] = finalists_sorted[elem]
    
    # стартовый лист финалистов fnl_start_list (в обратном порядке, от 10го места до 1го места)
    for elem in lst_fnl_parti[::-1] :
        fnl_start_list.append(elem)
    
    # вывод на экран списка финалистов
    counter = 1
    for elem in finalists:
        cycle_dict = {  0: [f'{counter}.', base_color, 4], 
                        0.4: [elem, base_color, 5], 
                        0.9: [finalists[elem][0], base_color, 40],
                        3: [finalists[elem][1], base_color, 20],
                        4.6: [finalists[elem][-1][-1], base_color, 4]}
        for key in cycle_dict:
            lbl = Label(final_window, background=cycle_dict[key][1], foreground='black', font=(font_name, 8), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart + key * xmove) , y = (ystart + ymove * counter))
        counter += 1

# кнопка с третьего окна, которая закрывает 3-е окно и открывает 4-е
btn_finish_semifinal = Button(semifinal_window, text = 'Завершить полуфинал', background=base_color, command = start_final) # кнопка "Завершить полуфинал" !!!
# -------------------------------------------------------------------------------------------------------------------------


sequens_fnl = [1] # список для контроля текущего участника, по len() определим порядковый номер (т.е. [1, 1, 1] - это 3-ий)
fnl_number = [] # здесь будет храниться <номер> участника для взаимосвязи функции button_work_final() с функцией throw_seria_fnl()
# -----------ФУНКЦИЯ КНОПКИ "НАЧАТЬ" и "следующий" ФИНАЛ----------------------------------
def button_work_final():
    btn_start_final.destroy() # убираем кнопку "НАЧАТЬ"
    
    ###### находим <номер> следующего участника (key_number)   
    sequens_number = len(sequens_fnl) - 1
    key_number = fnl_start_list[sequens_number]
    ###################################
    
    info_label = Label(final_window, text = f'{key_number}', background=base_color, font=(font_name, 16)) # лейбл с <номером> участника
    info_label.place(x=430, y=60) 
    name_label = Label(final_window, text = finalists[key_number][0], background=base_color, font=(font_name, 30)) # лейбл с <именем-фамилией> участника
    name_label.place(x=480, y=50)
    locality_label = Label(final_window, text = finalists[key_number][1], background=base_color, font=(font_name, 18)) # лейбл с <локалити> участника
    locality_label.place(x=550, y=100)
    score_label = Label(final_window, text = finalists[key_number][-1][-1], background=base_color, font=(font_name, 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    ###### находим целевые <очки> следующего участника (key_number)
    finalists_sort = dict(sorted(finalists.items(), key = lambda x: x[-1][-1][-1], reverse=True))  
    finalists_lst = list(finalists_sort)
    finalists.clear()
    for elem in finalists_lst:
        finalists[elem] = finalists_sort[elem]
    first_key = finalists_lst[0]
    if first_key == key_number: # если <номер> лидера и есть номер текущего участника,
        second_key = finalists_lst[1] # то находим <номер> участника на 2-ом месте (second_key)
        points_score = finalists[key_number][-1][1] - finalists[second_key][-1][1] # и рассчитываем имеющееся преимущество лидера
        goal_throw_fnl1_lbl = Label(final_window, text='имеющееся', background=base_color, font=(font_name, 12), width = 12) # лейбл "имеющееся"          !!!
        goal_throw_fnl2_lbl = Label(final_window, text='преимущество', background=base_color, font=(font_name, 12), width = 12) # лейбл "преимущество:"          !!!
        goal_throw_fnl1_lbl.place(x=790, y=100)          # лейбл "имеющееся"          !!!
        goal_throw_fnl2_lbl.place(x=790, y=120)          # лейбл "преимущество:"          !!!
    else: # иначе же вычитаем из <очков> лидера <очки> текущего участника
        points_score = finalists[first_key][-1][1] - finalists[key_number][-1][1]
        goal_throw_fnl1_lbl = Label(final_window, text='до 1-го места', background=base_color, font=(font_name, 12), width = 12) # лейбл "до 1-го места"          !!!
        goal_throw_fnl2_lbl = Label(final_window, text='необходимо', background=base_color, font=(font_name, 12), width = 12) # лейбл "необходимо:"          !!!
        goal_throw_fnl1_lbl.place(x=790, y=100)          # лейбл "до 1-го места"          !!!
        goal_throw_fnl2_lbl.place(x=790, y=120)          # лейбл "необходимо:"          !!!
    
    points_label = Label(final_window, text = points_score, background=base_color, font=(font_name, 18), width = 6)     # лейбл целевого количества очков
    points_label.place(x=910, y=110) 
    
    ###################################
    
    sequens_fnl.append(1) # в список добавляем единицу, чтобы увеличить len() и контролировать порядок текущего участника
    
    ###### для взаимосвязи с функцией throw_seria_fnl() очищаем список fnl_number и добавляем в него <номер> текущего участника
    fnl_number.clear() 
    fnl_number.append(key_number)
    ###################################
    
    btn_next_final.place(x=850, y=180) # выводим кнопку "следующий"

# -----------ФУНКЦИЯ КНОПКИ "НАЧАТЬ" и "следующий" ФИНАЛ---------КОНЕЦ-------------------------


fnl_after_throw = [] # список финалистов, которые начали выполнять свои броски
#throw_cycle_lst = [1] # список контроля серии бросков с помощью len() от 1 до 5 (т.е. от [1] до [1, 1, 1, 1, 1]) УЖЕ СОЗДАН РАНЕЕ
# -----------ФУНКЦИЯ КНОПКИ "ЗАПИСАТЬ" В ФИНАЛЕ----------------------------------
def throw_seria_fnl():
    key_number = fnl_number[0] # сохранённый в списке fnl_number <номер> участника заводим в функцию (в key_number)
    throw_total = finalists[key_number][-1][1]

    # из полей ввода соберём все данные о 3-х бросках, найдём их сумму и прибавим к общей сумме
    throw_1 = int( throw1_fnl_ent.get() )
    throw_2 = int( throw2_fnl_ent.get() )
    throw_3 = int( throw3_fnl_ent.get() )
    throw_seria = throw_1 + throw_2 + throw_3
    throw_total = throw_total + throw_seria
    seria_ent = (throw_seria, throw_total) # сделаем кортеж с суммой в серии и общей суммой
    finalists[key_number].append(seria_ent) # добавим этот кортеж в список участника по его ключу <номеру>
    ###################################
    
    ###### отсортируем получившийся словарь по общей сумме очков и создадим список finalists_lst с отсортированными <номерами> участников 
    finalists_sort = dict(sorted(finalists.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    finalists_lst = list(finalists_sort)
    finalists.clear()
    for elem in finalists_lst:
            finalists[elem] = finalists_sort[elem]
    ###################################
    
    ###### лейбл с мониторингом целевых очков для выхода на 1-ое место
    first_key = finalists_lst[0]
    if first_key == key_number: # если <номер> лидера и есть <номер> текущего участника, то меняем лейбл на "новое преимущество:"
        superiority1_lbl = Label(final_window, text = 'новое', background=base_color, font=(font_name, 12), width = 12) # лейбл "новое"          !!!
        superiority2_lbl = Label(final_window, text = 'преимущество:', background=base_color, font=(font_name, 12), width = 12) # лейбл "преимущество:"          !!!
        superiority1_lbl.place(x=790, y=100)  
        superiority2_lbl.place(x=790, y=120)
        second_key = finalists_lst[1] # находим <номер> участника на 2-ом месте (second_key)
        points_score = finalists[key_number][-1][1] - finalists[second_key][-1][1] # и рассчитываем преимущество нового лидера
    else: # если текущий участник не стал новым лидером, то ищем его целевые очки как разницу от очков лидера
        points_score = finalists[first_key][-1][1] - finalists[key_number][-1][1]
       
    points_label = Label(final_window, text = points_score, background=base_color, font=(font_name, 18), width = 6)     # число, вывод целевого количества очков
    points_label.place(x=910, y=110)      # число, вывод целевого количества очков
    ###################################
    
    counter_fnl = 1
    fnl_after_throw.append(key_number)
    for elem in finalists_lst:
        if elem == key_number: parti_color = active_color
        else: parti_color = base_color
        if elem in fnl_after_throw:
            sum_throw = len(finalists[elem]) - 2
            cycle_dict = {  0: [f'{counter_fnl}.', parti_color, 4],         # вывод порядкового номера, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                            0.4: [elem, parti_color, 5],                 # вывод номера участника, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                            0.9: [finalists[elem][0], parti_color, 40], # вывод имя-фамилия
                            4: [finalists[elem][1], parti_color, 20],  # вывод локалити
                            6.5: [(finalists[elem][12][0] if sum_throw >= 11 else ' '), parti_color, 3],    # вывод серия 1
                            6.9: [(finalists[elem][13][0] if sum_throw >= 12 else ' '), parti_color, 3],    # вывод серия 2
                            7.3: [(finalists[elem][14][0] if sum_throw >= 13 else ' '), parti_color, 3],    # вывод серия 3
                            7.7: [(finalists[elem][15][0] if sum_throw >= 14 else ' '), parti_color, 3],    # вывод серия 4
                            8.1: [(finalists[elem][16][0] if sum_throw >= 15 else ' '), parti_color, 3],    # вывод серия 5
                            8.5: [finalists[elem][-1][1], 'pink', 2],    # вывод серия тотал
                            }
            for key in cycle_dict:
                lbl = Label(final_window, background=cycle_dict[key][1], foreground='black', font=(font_name, 15), width = cycle_dict[key][2])
                lbl['text'] = cycle_dict[key][0]
                lbl.place( x = (xstart2 + key * xmove2) , y = (ystart2 + ymove2 * counter_fnl))                   
            counter_fnl += 1
    
    score_label = Label(final_window, text = finalists[key_number][-1][-1], background=base_color, font=(font_name, 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    throw1_fnl_ent.delete(0, END)
    throw2_fnl_ent.delete(0, END)
    throw3_fnl_ent.delete(0, END)
    if len(throw_cycle_lst) == 5:
        fnl_number.clear()
        throw_cycle_lst.clear()
        throw_cycle_lst.append(1)
    else: throw_cycle_lst.append(1)
# -----------ФУНКЦИЯ КНОПКИ ЗАПИСАТЬ В ФИНАЛЕ---------КОНЕЦ-------------------------

heading_4_lbl = Label(final_window, text='ФИНАЛ', background=base_color, font=(font_name, 20)) # "ФИНАЛ"          !!!
finalist_list_lbl = Label(final_window, text='Список финалистов', background=base_color, font=(font_name, 18)) # "Список финалистов"      !!!
throwing_final_lbl = Label(final_window, text='Броски:', background=base_color, font=(font_name, 13)) # "Броски"         !!!
throw_serial_final_lbl = Label(final_window, text = f'Запись бросков, серия {len(throw_cycle_lst)}:', background=base_color, font=(font_name, 12)) # лейбл "Запись бросков, серия НОМЕР" !!!

throw1_fnl_ent = Entry(final_window, width = 7) # поле ввода "Бросок 1"      !!!
throw2_fnl_ent = Entry(final_window, width = 7) # поле ввода "Бросок 2"      !!!
throw3_fnl_ent = Entry(final_window, width = 7) # поле ввода "Бросок 3"      !!!

btn_start_final = Button(final_window, text = 'НАЧАТЬ', background=base_color, width = 16, command = button_work_final) # кнопка "НАЧАТЬ" !!!
btn_throw_seria_final = Button(final_window, text = 'Записать', background=base_color, width = 9, command = throw_seria_fnl) # кнопка "Записать"  !!!
btn_next_final = Button(final_window, text = 'следующий', background=base_color, width = 16, command = button_work_final) # кнопка "следующий"    !!!


root.mainloop()

In [ ]:
fffff = {
    153: ['Антон Озерин', 'Волжский', (12, 12), (18, 30), (15, 45), (17, 62), (9, 71), (9, 80), (10, 90), (9, 99), (10, 109), (11, 120)], 
    692: ['Сергей Сивков', 'Октябрьский', (12, 12), (13, 25), (18, 43), (12, 55), (13, 68), (9, 77), (15, 92), (14, 106), (14, 120), (9, 129)], 
    569: ['Виктор Елагин', 'Волжский', (12, 12), (9, 21), (13, 34), (14, 48), (12, 60), (8, 68), (10, 78), (12, 90), (12, 102), (13, 115)], 
    944: ['Сергей Голубин', 'Кировский', (10, 10), (14, 24), (12, 36), (12, 48), (9, 57), (13, 70), (15, 85), (12, 97), (14, 111), (13, 124)], 
    802: ['Николай Сюсюкин', 'Ворошиловский', (12, 12), (14, 26), (10, 36), (14, 50), (6, 56), (14, 70), (12, 82), (15, 97), (16, 113), (13, 126)], 
    342: ['Андрей Трегубов', 'Краснооктябрьский', (12, 12), (6, 18), (12, 30), (10, 40), (15, 55), (14, 69), (15, 84), (13, 97), (15, 112), (13, 125)], 
    737: ['Александр Файзулин', 'Дзержинский', (15, 15), (9, 24), (10, 34), (9, 43), (11, 54), (7, 61), (11, 72), (11, 83), (14, 97), (12, 109)], 
    371: ['Кирилл Агапов', 'Калач-на-дону', (12, 12), (9, 21), (10, 31), (9, 40), (12, 52), (14, 66), (10, 76), (10, 86), (14, 100), (10, 110)], 
    410: ['Станислав Гриднев', 'Фролово', (10, 10), (8, 18), (10, 28), (11, 39), (9, 48), (14, 62), (13, 75), (13, 88), (13, 101), (13, 114)]}

{153: ['Антон Озерин', 'Волжский', (12, 12), (18, 30), (15, 45), (17, 62), (9, 71), (9, 80), (10, 90), (9, 99), (10, 109), (11, 120)], 692: ['Сергей Сивков', 'Октябрьский', (12, 12), (13, 25), (18, 43), (12, 55), (13, 68), (9, 77), (15, 92), (14, 106), (14, 120), (9, 129)], 569: ['Виктор Елагин', 'Волжский', (12, 12), (9, 21), (13, 34), (14, 48), (12, 60), (8, 68), (10, 78), (12, 90), (12, 102), (13, 115)], 944: ['Сергей Голубин', 'Кировский', (10, 10), (14, 24), (12, 36), (12, 48), (9, 57), (13, 70), (15, 85), (12, 97), (14, 111), (13, 124)], 802: ['Николай Сюсюкин', 'Ворошиловский', (12, 12), (14, 26), (10, 36), (14, 50), (6, 56), (14, 70), (12, 82), (15, 97), (16, 113), (13, 126)], 342: ['Андрей Трегубов', 'Краснооктябрьский', (12, 12), (6, 18), (12, 30), (10, 40), (15, 55), (14, 69), (15, 84), (13, 97), (15, 112), (13, 125)], 737: ['Александр Файзулин', 'Дзержинский', (15, 15), (9, 24), (10, 34), (9, 43), (11, 54), (7, 61), (11, 72), (11, 83), (14, 97), (12, 109), (10, 119), (8, 127), (9, 136)], 371: ['Кирилл Агапов', 'Калач-на-дону', (12, 12), (9, 21), (10, 31), (9, 40), (12, 52), (14, 66), (10, 76), (10, 86), (14, 100), (10, 110), (9, 119), (15, 134)], 410: ['Станислав Гриднев', 'Фролово', (10, 10), (8, 18), (10, 28), (11, 39), (9, 48), (14, 62), (13, 75), (13, 88), (13, 101), (13, 114), (11, 125), (15, 140), (11, 151)]}

In [ ]:
finalists = {
    1: ['Первый Иванов', 'Красноярск', (8, 8), (10, 18), (12, 30), (12, 42), (12, 54)],
    2: ['Второй Петров', 'Омск', (10, 10), (13, 23), (10, 33), (7, 40), (12, 52)],
    3: ['Третий Сидоров', 'Тюмень', (14, 14), (12, 26), (16, 42), (18, 60), (19, 79)],
    4: ['Четвёртый Кузнецов', 'Иркутск', (10, 10), (12, 22), (15, 37), (14, 51), (15, 66)],
    5: ['Пятый Фролов', 'Киров', (12, 12), (14, 26), (12, 38), (17, 55), (16, 71)],
    6: ['Шестой Смирнов', 'Якутск', (18, 18), (4, 22), (8, 30), (8, 38), (10, 48)],
    7: ['Седьмой Дубов', 'Мурманск', (15, 15), (13, 28), (13, 41), (17, 58), (18, 76)]}

##### временный код для разработки
for elem in list(finalists)[::-1] :
    fnl_start_list.append(elem)
#############################

# -----------ФУНКЦИЯ КНОПКИ "ЗАПИСАТЬ" В ФИНАЛЕ----------------------------------
def throw_seria_fnl():
    key_number = fnl_number[0] # сохранённый в списке fnl_number <номер> участника заводим в функцию (в key_number)
    
    ###### разбираемся с общей суммой очков текущего участника
    if len(throw_cycle_lst) == 1:   # если это 1-ая серия бросков,  
                                    # то в словарь fnl_parti вносим всю информацию об участнике и сумме его очков
        throw_total = finalists[key_number][-1][1]
    else: # если броски 2ой-5ой серии, то сумму очков берём из fnl_parti
        throw_total = fnl_parti[key_number][-1][1]
    # из полей ввода соберём все данные о 3-х бросках, найдём их сумму и прибавим к общей сумме
    throw_1 = int( throw1_fnl_ent.get() )
    throw_2 = int( throw2_fnl_ent.get() )
    throw_3 = int( throw3_fnl_ent.get() )
    throw_seria = throw_1 + throw_2 + throw_3
    throw_total = throw_total + throw_seria
    seria_ent = (throw_seria, throw_total) # сделаем кортеж с суммой в серии и общей суммой
    fnl_parti[key_number].append(seria_ent) # добавим этот кортеж в список участника по его ключу <номеру>
    ###################################
    
    ###### отсортируем получившийся словарь по общей сумме очков и создадим список fnl_parti_lst с отсортированными <номерами> участников 
    fnl_parti_sort = dict(sorted(fnl_parti.items(), key = lambda x: x[-1][-1][-1], reverse=True))
    fnl_parti_lst = list(fnl_parti_sort)
    ###################################
    
    ###### лейбл с мониторингом целевых очков для выхода на 1-ое место
    if len(fnl_parti_lst) == 1 :         # если это первый финалист (и, соответственно, в списке fnl_parti_lst всего один участник),
        points_score = 0                # то у него в целевых очках ноль
    else: # иначе же находим <номер> лидера (first_key)
        first_key = fnl_parti_lst[0]
        if first_key == key_number: # если <номер> лидера и есть <номер> текущего участника, то меняем лейбл на "новое преимущество:"
            superiority1_lbl = ttk.Label(final_window, text = 'новое', background='yellow', font=('Arial', 12), width = 12) # лейбл "новое"          !!!
            superiority2_lbl = ttk.Label(final_window, text = 'преимущество:', background='yellow', font=('Arial', 12), width = 12) # лейбл "преимущество:"          !!!
            superiority1_lbl.place(x=790, y=100)  
            superiority2_lbl.place(x=790, y=120)
            second_key = fnl_parti_lst[1] # находим <номер> участника на 2-ом месте (second_key)
            points_score = fnl_parti_sort[key_number][-1][1] - fnl_parti_sort[second_key][-1][1] # и рассчитываем преимущество нового лидера
        else: # если текущий участник не стал новым лидером, то ищем его целевые очки как разницу от очков лидера
            points_score = fnl_parti_sort[first_key][-1][1] - fnl_parti_sort[key_number][-1][1]
       
    points_label = ttk.Label(final_window, text = points_score, font=('Arial', 18), width = 6)     # число, вывод целевого количества очков
    points_label.place(x=910, y=110)      # число, вывод целевого количества очков
    ###################################
    
    counter_fnl = 1
    for elem in fnl_parti_lst:
        sum_throw = len(fnl_parti[elem]) - 2
        cycle_dict = {  0: [counter_fnl, 'yellow', 4],         # вывод порядкового номера, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.4: [elem, 'pink', 5],                 # вывод номера участника, в ключе - смещение по x, сам вывод, цвет, ширина лейбла
                        0.9: [fnl_parti[elem][0], 'blue', 40], # вывод имя-фамилия
                        4: [fnl_parti[elem][1], 'green', 20],  # вывод локалити
                        6.5: [fnl_parti[elem][7][0], 'pink', 3],    # вывод серия 1
                        6.9: [(fnl_parti[elem][8][0] if sum_throw >= 7 else ' '), 'blue', 3],    # вывод серия 2
                        7.3: [(fnl_parti[elem][9][0] if sum_throw >= 8 else ' '), 'yellow', 3],    # вывод серия 3
                        7.7: [(fnl_parti[elem][10][0] if sum_throw >= 9 else ' '), 'green', 3],    # вывод серия 4
                        8.1: [(fnl_parti[elem][11][0] if sum_throw >= 10 else ' '), 'blue', 3],    # вывод серия 5
                        8.5: [fnl_parti[elem][-1][1], 'pink', 2],    # вывод серия тотал
                        }
        for key in cycle_dict:
            lbl = ttk.Label(final_window, background=cycle_dict[key][1], foreground='black', font=('Arial', 15), width = cycle_dict[key][2])
            lbl['text'] = cycle_dict[key][0]
            lbl.place( x = (xstart2 + key * xmove2) , y = (ystart2 + ymove2 * counter_fnl))                   
        counter_fnl += 1
    
    score_label = ttk.Label(final_window, text = fnl_parti[key_number][-1][-1], background='yellow', font=('Arial', 37), width = 4) # лейбл с <очками> участника
    score_label.place(x=870, y=40)
    
    throw1_fnl_ent.delete(0, END)
    throw2_fnl_ent.delete(0, END)
    throw3_fnl_ent.delete(0, END)
    if len(throw_cycle_lst) == 5:
        fnl_number.clear()
        throw_cycle_lst.clear()
        throw_cycle_lst.append(1)
    else: throw_cycle_lst.append(1)
# -----------ФУНКЦИЯ КНОПКИ ЗАПИСАТЬ В ФИНАЛЕ---------КОНЕЦ-------------------------

In [ ]:
qual_parti2

In [701]:
# 3-е ОКНО, ПОЛУФИНАЛ, БРОСКИ 10 ЛУЧШИХ В КВАЛИФИКАЦИИ
from tkinter import *
from tkinter import ttk

root3 = Tk()
root3.geometry('1000x600')

root3.title('Соревнования по дартс')
#root.attributes('-fullscreen', True)

#заголовок Список участников
heading = ttk.Label(root3, text='Список участников', font=('Arial', 18))
heading.place(x=100, y=10)

#заголовок Квалификация
heading = ttk.Label(root3, text='Квалификация', font=('Arial', 20))
heading.place(x=600, y=10)

#заголовки Номер участника и Броски
number_participant = ttk.Label(text='Номер участника', font=('Arial', 13))
number_participant.place(x=550,y=60)
throwing = ttk.Label(text='Броски:', font=('Arial', 13))
throwing.place(x=550,y=90)




root3.mainloop()

In [ ]:
# просто сохранил словарь на всякий случай
participants = {
    832: ['Иван Бочеров', 'Волжский'],
    731: ['Андрей Трегубов', 'Краснооктябрьский'],
    583: ['Виктор Елагин', 'Волжский'],
    410: ['Станислав Гриднев', 'Фролово'],
    737: ['Александр Файзулин', 'Дзержинский'],
    298: ['Антон Озерин', 'Волжский']
    }

qual_parti1 = {
    832: ['Иван Бочеров', 'Волжский', (16), (17, 33), (26, 59), (10, 69), (23, 1)],
    731: ['Андрей Трегубов', 'Краснооктябрьский', (16), (17, 33), (26, 59), (10, 69), (23, 2)],
    583: ['Виктор Елагин', 'Волжский', (16), (17, 33), (26, 59), (10, 69), (23, 3)],
    410: ['Станислав Гриднев', 'Фролово', (16), (17, 33), (26, 59), (10, 69), (23, 4)],
    737: ['Александр Файзулин', 'Дзержинский', (16), (17, 33), (26, 59), (10, 69), (23, 5)],
    298: ['Антон Озерин', 'Волжский', (16), (17, 33), (26, 59), (10, 69), (23, 6)]
    }

In [628]:
for elem in qual_parti1:
    print(qual_parti1[elem][-1][1])

5
6
1
2
3
4

In [548]:
participants

{731: ['Андрей Трегубов', 'Краснооктябрьский'],
 583: ['Виктор Елагин', 'Волжский'],
 410: ['Станислав Гриднев', 'Фролово'],
 737: ['Александр Файзулин', 'Дзержинский'],
 298: ['Антон Озерин', 'Волжский']}

In [610]:
qual_parti

{832: ['Иван Бочеров',
  'Волжский',
  (14, 14),
  (14, 28),
  (14, 42),
  (14, 56),
  (14, 70)],
 410: ['Станислав Гриднев',
  'Фролово',
  (15, 15),
  (52, 67),
  (4, 71),
  (7, 78),
  (13, 91)],
 737: ['Александр Файзулин',
  'Дзержинский',
  (17, 17),
  (15, 32),
  (14, 46),
  (353, 399),
  (17, 416)],
 583: ['Виктор Елагин',
  'Волжский',
  (16, 16),
  (11, 27),
  (13, 40),
  (68, 108),
  (15, 123)]}

In [603]:
qual_number

[410]

In [90]:
# работаю над циклом при выведении лейблов
from tkinter import *
from tkinter import ttk

root = Tk()
root.geometry('1000x600')

dct = {}
xstart = 0
ystart = 0
xmove = 10
ymove = 10

def enter_note():
    number = entr1.get()
    name = entr2.get()
    dct[number] = [name]
    sort_dct = dict(sorted(dct.items()))
    lst_dct = list(sort_dct)
    cntr = 1
    for elem in lst_dct:
        lbel6['text'] = f'{cntr}.'
        lbel6.place( x = (xstart + xmove * cntr) , y = (ystart + ymove * cntr) )
        lbel1['text'] = elem
        lbel1.place( x = (xstart + xmove * cntr) , y = (ystart + ymove * cntr + 20) )
        lbel2['text'] = dct[elem][0]
        lbel2.place( x = (xstart + xmove * cntr) , y = (ystart + ymove * cntr + 40) )
        lbel3['text'] = dct[elem][1]
        lbel3.place( x = (xstart + xmove * cntr) , y = (ystart + ymove * cntr + 60) )
        lbel4['text'] = dct[elem][2]
        lbel4.place( x = (xstart + xmove * cntr) , y = (ystart + ymove * cntr + 80) )
        lbel5['text'] = dct[elem][3]
        lbel5.place( x = (xstart + xmove * cntr) , y = (ystart + ymove * cntr + 1000) )
        entr1.delete(0, END)
        entr2.delete(0, END)


entr1 = ttk.Entry(root)
entr1.pack()
entr2 = ttk.Entry(root)
entr2.pack()

btn = ttk.Button(root, text='Зарегистрировать', command=enter_note)
btn.pack()

entr3 = ttk.Entry(root)
entr3.pack(anchor='c')
entr4 = ttk.Entry(root)
entr4.pack(anchor='c')
entr5 = ttk.Entry(root)
entr5.pack(anchor='c')

btn2 = ttk.Button(root, text='Записать броски', command=enter_throwing)
btn2.pack(anchor='c')




root.mainloop()

Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\azott\AppData\Local\Temp\ipykernel_9380\286688787.py", line 22, in enter_note
    lbel6['text'] = f'{cntr}.'
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1657, in __setitem__
    self.configure({key: value})
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!label6"
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\azott\AppData\Local\Temp\ipykernel_9380\286688787.py", line 22, in enter_note
    lbel6['text'] = f'{cntr}.'
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1657, in __setitem__
    self.configure({key: value})
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!label6"
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\azott\AppData\Local\Temp\ipykernel_9380\286688787.py", line 22, in enter_note
    lbel6['text'] = f'{cntr}.'
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1657, in __setitem__
    self.configure({key: value})
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "c:\Users\azott\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!label6"

стартовый экран квалификации

In [133]:
from tkinter import *
from tkinter import ttk

root = Tk()
root.geometry("1350x650")
root.title('Соревнования по дартс')
#root.attributes('-fullscreen', True)
for c in range(8): root.columnconfigure(index=c, weight=1)
for r in range(15): root.rowconfigure(index=r, weight=1)
#заголовок Квалификация
heading = ttk.Label(text='Квалификация', font=('Arial', 18))
heading.grid(column=0, columnspan=4, row=0)
#заголовок Ввод участника
entry_participant = ttk.Label(text='Ввод участника', font=('Arial', 17))
entry_participant.grid(column=5, columnspan=4, row=0)
#номер участника
number_lbl = ttk.Label(text='номер', font=('Arial', 14))
number_lbl.grid(column=5, row=1, sticky='w')
number = ttk.Entry()
number.grid(column=6, row=1, ipadx=50)
#введение имени
name_lbl = ttk.Label(text='имя', font=('Arial', 14))
name_lbl.grid(column=5, row=2, sticky='w')
name = ttk.Entry()
name.grid(column=6, row=2, ipadx=50)
#введение фамилии
lastname_lbl = ttk.Label(text='фамилия', font=('Arial', 14))
lastname_lbl.grid(column=5, row=3, sticky='w')
lastname = ttk.Entry()
lastname.grid(column=6, row=3, ipadx=50)
#введение населённого пункта, который участник представляет
location_lbl = ttk.Label(text='населённый пункт', font=('Arial', 14))
location_lbl.grid(column=5, row=4, sticky='w')
location = ttk.Entry()
location.grid(column=6, row=4, ipadx=50)
#заголовок "Броски"
throwing_lbl = ttk.Label(text='Броски:', font=('Arial', 14))
throwing_lbl.grid(column=5, columnspan=4, row=5, sticky='w')

col = 5
n = range(col)
m = range(3)

for n_elem in n:
    throw = n_elem + 1
    throwing_lbl = ttk.Label(text=f'{throw}:', font=('Arial', 14))
    throwing_lbl.grid(column=5, row=n_elem+6, sticky='w')
    for m_elem in m:
        throwing = ttk.Entry()
        throwing.grid(column=m_elem+6, row=n_elem+6, ipadx=10, sticky='w')

partic=[
    (832, 'Иван Бочеров', 'Волжский'),
    (731, 'Андрей Трегубов', 'Краснооктябрьский'),
    (583, 'Виктор Елагин', 'Волжский'),
    (410, 'Станислав Гриднев', 'Фролово'),
    (737, 'Александр Файзулин', 'Дзержинский'),
    (298, 'Антон Озерин', 'Волжский')
    ]

mycol=('number', 'name', 'location')

mytable = ttk.Treeview(columns=mycol, show="headings")

#mytable.insert("", END, values=partic)
mytable.grid(columns=1, columnspan=4, row=2, rowspan=7)

mytable.heading('number', text='номер')
mytable.heading('name', text='имя-фамилия')
mytable.heading('location', text='населённый пункт')

for person in partic:
    mytable.insert("", END, values=person)

root.mainloop()

участники DataFrame

In [39]:
headlines = ['номер', 'имя-фамилия', 'населённвй пункт']
print("{:<7} {:<23} {:<15}".format(*headlines))

participants = {}
counter = -1

while True:
    name = input('Введите имя и фамилию участника')
    if name == 'конец':
        break
    else:
        locality = input('Какой населённый пункт представляет')
        number = input('Номер участника')
        counter += 1
        participants[number] = [name, locality]
        print("{:<7} {:<23} {:<15}".format(*participants[number]))

номер   имя-фамилия             населённвй пункт

IndexError: Replacement index 2 out of range for positional args tuple

In [61]:
import pandas as pd

partici = pd.DataFrame(
    data=(
    [832, 'Иван Бочеров', 'Волжский'],
    [731, 'Андрей Трегубов', 'Краснооктябрьский'],
    [583, 'Виктор Елагин', 'Волжский'],
    [410, 'Станислав Гриднев', 'Фролово'],
    [737, 'Александр Файзулин', 'Дзержинский'],
    [298, 'Антон Озерин', 'Волжский']),
    columns=['номер', 'имя-фамилия', 'населённый пункт'])

display(partici)

   номер         имя-фамилия   населённый пункт
0    832        Иван Бочеров           Волжский
1    731     Андрей Трегубов  Краснооктябрьский
2    583       Виктор Елагин           Волжский
3    410   Станислав Гриднев            Фролово
4    737  Александр Файзулин        Дзержинский
5    298        Антон Озерин           Волжский

In [64]:
partici = pd.DataFrame(
    data=(
    ['Иван Бочеров', 'Волжский'],
    ['Андрей Трегубов', 'Краснооктябрьский'],
    ['Виктор Елагин', 'Волжский'],
    ['Станислав Гриднев', 'Фролово'],
    ['Александр Файзулин', 'Дзержинский'],
    ['Антон Озерин', 'Волжский']),
    columns=['имя-фамилия', 'населённый пункт'],
    index=[832, 731, 583, 410, 737, 298])

display(partici)

            имя-фамилия   населённый пункт
832        Иван Бочеров           Волжский
731     Андрей Трегубов  Краснооктябрьский
583       Виктор Елагин           Волжский
410   Станислав Гриднев            Фролово
737  Александр Файзулин        Дзержинский
298        Антон Озерин           Волжский

In [5]:
#переделано на лучше
from tkinter import *
from tkinter import ttk

root = Tk()
root.geometry("1350x650")
root.title('Соревнования по дартс')
#root.attributes('-fullscreen', True)
for c in range(8): root.columnconfigure(index=c, weight=1)
for r in range(15): root.rowconfigure(index=r, weight=1)
#заголовок Квалификация
heading = ttk.Label(text='Квалификация', font=('Arial', 18))
heading.grid(column=0, columnspan=4, row=0)
#заголовок Ввод участника
entry_participant = ttk.Label(text='Ввод участника', font=('Arial', 17))
entry_participant.grid(column=5, columnspan=4, row=0)
#номер участника
number_lbl = ttk.Label(text='номер', font=('Arial', 14))
number_lbl.grid(column=5, row=1, sticky='w')
number = ttk.Entry()
number.grid(column=6, row=1, ipadx=50)
#введение имени
name_lbl = ttk.Label(text='имя', font=('Arial', 14))
name_lbl.grid(column=5, row=2, sticky='w')
name = ttk.Entry()
name.grid(column=6, row=2, ipadx=50)
#введение фамилии
lastname_lbl = ttk.Label(text='фамилия', font=('Arial', 14))
lastname_lbl.grid(column=5, row=3, sticky='w')
lastname = ttk.Entry()
lastname.grid(column=6, row=3, ipadx=50)
#введение населённого пункта, который участник представляет
location_lbl = ttk.Label(text='населённый пункт', font=('Arial', 14))
location_lbl.grid(column=5, row=4, sticky='w')
location = ttk.Entry()
location.grid(column=6, row=4, ipadx=50)
#заголовок "Броски"
throwing_lbl = ttk.Label(text='Броски:', font=('Arial', 14))
throwing_lbl.grid(column=5, columnspan=4, row=5, sticky='w')
#броски 1-ой серии
throwing1_lbl = ttk.Label(text='1:', font=('Arial', 14))
throwing1_lbl.grid(column=5, row=6, sticky='w')
throwing_1_1 = ttk.Entry()
throwing_1_1.grid(column=6, row=6, ipadx=20, sticky='w')
throwing_1_2 = ttk.Entry()
throwing_1_2.grid(column=7, row=6, ipadx=50, sticky='w')
throwing_1_3 = ttk.Entry()
throwing_1_3.grid(column=8, row=6, ipadx=80, sticky='w')
#броски 2-ой серии
throwing2_lbl = ttk.Label(text='2:', font=('Arial', 14))
throwing2_lbl.grid(column=5, row=7, sticky='w')
throwing_2_1 = ttk.Entry()
throwing_2_1.grid(column=6, row=7, ipadx=20, sticky='w')
throwing_2_2 = ttk.Entry()
throwing_2_2.grid(column=7, row=7, ipadx=50, sticky='w')
throwing_2_3 = ttk.Entry()
throwing_2_3.grid(column=8, row=7, ipadx=80, sticky='w')
#броски 3-ей серии
throwing3_lbl = ttk.Label(text='3:', font=('Arial', 14))
throwing3_lbl.grid(column=5, row=8, sticky='w')
#броски 4-ой серии
throwing4_lbl = ttk.Label(text='4:', font=('Arial', 14))
throwing4_lbl.grid(column=5, row=9, sticky='w')
#броски 5-ой серии
throwing5_lbl = ttk.Label(text='5:', font=('Arial', 14))
throwing5_lbl.grid(column=5, row=10, sticky='w')

partic=[
    (832, 'Иван Бочеров', 'Волжский'),
    (731, 'Андрей Трегубов', 'Краснооктябрьский'),
    (583, 'Виктор Елагин', 'Волжский'),
    (410, 'Станислав Гриднев', 'Фролово'),
    (737, 'Александр Файзулин', 'Дзержинский'),
    (298, 'Антон Озерин', 'Волжский')
    ]

mycol=('number', 'name', 'location')

mytable = ttk.Treeview(columns=mycol, show="headings")

#mytable.insert("", END, values=partic)
mytable.grid(columns=1, columnspan=4, row=2, rowspan=7)

mytable.heading('number', text='номер')
mytable.heading('name', text='имя-фамилия')
mytable.heading('location', text='населённый пункт')

for person in partic:
    mytable.insert("", END, values=person)


root.mainloop()

In [115]:
#поигрался с фреймом и рутом
root = Tk()
root.geometry("650x350")

canvas = Canvas(root, height=300, width=250)
canvas.pack()

frame = Frame(root, bg='blue')
frame.place(relx=0.1, rely=0.1, relwidth=0.3, relheight=0.1)

title = Label(frame, text = 'А вот и я')
title.pack()

root.mainloop()

In [111]:
import tkinter as tk

sample_df = pd.DataFrame(
    data=(
    [832, 'Иван Бочеров', 'Волжский'],
    [731, 'Андрей Трегубов', 'Краснооктябрьский'],
    [583, 'Виктор Елагин', 'Волжский'],
    [410, 'Станислав Гриднев', 'Фролово'],
    [737, 'Александр Файзулин', 'Дзержинский'],
    [298, 'Антон Озерин', 'Волжский']),
    columns=['номер', 'имя-фамилия', 'населённый пункт'])

class TableEditor:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title('Таблица конструктор')
        
        self.frame = tk.Frame(self.root)
        self.frame.pack()
        
        self.table = Table(self.frame, showstatusbar=True, showtoolbar=True, dataframe=sample_df)
        self.table.show()
        
        self.root.mainloop()
        

if __name__ == '__main__':
    TableEditor()

TclError: image "pyimage87" doesn't exist

In [110]:
import pandas as pd
import tkinter as tk
from pandastable import Table

sample_df = pd.DataFrame(
    data=(
    [832, 'Иван Бочеров', 'Волжский'],
    [731, 'Андрей Трегубов', 'Краснооктябрьский'],
    [583, 'Виктор Елагин', 'Волжский'],
    [410, 'Станислав Гриднев', 'Фролово'],
    [737, 'Александр Файзулин', 'Дзержинский'],
    [298, 'Антон Озерин', 'Волжский']),
    columns=['номер', 'имя-фамилия', 'населённый пункт'])

class PandasApp():
    def __init__(self, master) -> None:
        self.frame = tk.Frame(master)
        self.frame.pack(padx=10, pady=10)
        
        self.table = Table(self.frame, dataframe=sample_df, showstatusbar=True, showtoolbar=True)
        self.table.show()
    
root = tk.Tk()
app = PandasApp(root)
root.mainloop()

TclError: image "pyimage86" doesn't exist

In [117]:
from tkinter import *
from pandastable import Table, TableModel, config
class TestApp(Frame):

    def __init__(self, parent=None):
        self.parent = parent
        Frame.__init__(self)
        self.main = self.master
        self.main.geometry('600x400+200+100')
        self.main.title('Table app')
        f = Frame(self.main)
        f.pack(fill=BOTH,expand=1)
        df = TableModel.getSampleData()
        self.table = pt = Table(f, dataframe=df,
        showtoolbar=True, showstatusbar=True)
        pt.show()
        #set some options
        options = {'colheadercolor':'green','floatprecision': 5}
        config.apply_options(options, pt)
        pt.show()
        return 
app = TestApp()
#launch the app
app.mainloop()

TclError: invalid command name ".!canvas"

In [1]:
#вариант из обучалки

root = Tk()
root.title("METANIT.COM")
root.geometry("250x200") 
 
# определяем данные для отображения
people = [("Tom", 38, "tom@email.com"), ("Bob", 42, "bob@email.com"), ("Sam", 28, "sam@email.com")]
 
# определяем столбцы
columns = ("name", "age", "email")
 
tree = ttk.Treeview(columns=columns, show="headings")
tree.pack(fill=BOTH, expand=1)
 
# определяем заголовки
tree.heading("name", text="Имя")
tree.heading("age", text="Возраст")
tree.heading("email", text="Email")
 
# добавляем данные
for person in people:
    tree.insert("", END, values=person)
 
root.mainloop()

NameError: name 'Tk' is not defined

In [ ]:
#пробую синтез двух кодов
root = Tk()
root.title("METANIT.COM")
root.geometry("650x350") 
 
# определяем данные для отображения
people = [
    [832, 'Иван Бочеров', 'Волжский'],
    [731, 'Андрей Трегубов', 'Краснооктябрьский'],
    [583, 'Виктор Елагин', 'Волжский'],
    [410, 'Станислав Гриднев', 'Фролово'],
    [737, 'Александр Файзулин', 'Дзержинский'],
    [298, 'Антон Озерин', 'Волжский']
    ]
 
# определяем столбцы
mycol = ('number', 'name', 'location')
 
tree = ttk.Treeview(columns=mycol, show="headings")
tree.pack(fill=BOTH, expand=1, )
 
# определяем заголовки
tree.heading("number", text="номер")
tree.heading("name", text="имя-фамилия")
tree.heading("location", text="населённый пункт")
 
# добавляем данные
for person in people:
    tree.insert("", END, values=person)
    
root.mainloop()